In [6]:
import pypsa
import pandas as pd
import numpy as np

In [2]:
n_base = pypsa.Network('base_s_1__none_2035_lt.nc')
n_lt = n_base.copy()

INFO:pypsa.io:Imported network base_s_1__none_2035_lt.nc has buses, carriers, generators, global_constraints, links, loads, storage_units, stores

In [31]:
horizon = 48
overlap = 0

# overlap 8 funktioniert super

nr_networks = 2

co2 preise adden:
- einmal ohne biomass: specific_emissions
- einmal mit biomass: specific_emissions_biomass

In [20]:
from typing import Dict, Any

co2_prices = {
    "2020": 28,
    "2025": 70,
    "2030": 130,
    "2035": 190,
    "2040": 210,
    "2045": 530,
}

specific_emissions = {
    "oil" : 0.2571,
    "oil primary" : 0.2571,
    "gas" : 0.198, # OCGT
    "gas primary" : 0.198, # OCGT
    "coal" : 0.3361,
    "lignite" : 0.4069,
}

specific_emissions_biomass = {
    "oil" : 0.2571,
    "oil primary" : 0.2571,
    "gas" : 0.198, # OCGT
    "gas primary" : 0.198, # OCGT
    "coal" : 0.3361,
    "lignite" : 0.4069,
    "solid biomass": 0.4
}

def add_carbon_price(n, co2_price, specific_emissions):
        
    for carrier in specific_emissions.keys():
        n.generators.loc[n.generators.carrier == carrier, "marginal_cost"] += (
            co2_price * specific_emissions[carrier]
        )

def build_st_network(n, e_initial_h2 = 1e6):

    # alle hydrogen related stores
    stores = n.stores[n.stores.carrier.str.contains("H2", case=False, na=False)].index

    # marginal price für alle der mean
    for i in stores:
        n.stores.loc[i, 'marginal_cost'] = n_base.buses_t.marginal_price['DE0 0 H2'].mean()
        n.stores.loc[i, 'e_cyclic'] = False


    n.stores.loc['DE0 0 H2 Store-2035', 'e_initial'] = e_initial_h2
    n.stores.loc['DE0 0 H2 Store-2030', 'e_initial'] = 0
    n.stores.loc['DE0 0 H2 Store-2020', 'e_initial'] = 0

    n.optimize.fix_optimal_capacities()
    n.optimize.create_model()

    return n

In [21]:
onwind_cf = pd.read_pickle('Wetterdaten/cappacity_factors_prepared/cf_onwind.pkl')
offwind_cf = pd.read_pickle('Wetterdaten/cappacity_factors_prepared/cf_offwind.pkl')
solar_cf = pd.read_pickle('Wetterdaten/cappacity_factors_prepared/cf_solar.pkl')

In [22]:
np.random.seed(1)

choice = np.random.choice(np.arange(0, 50), nr_networks, replace=False)

choice

array([27, 35, 40, 38,  2,  3])

In [23]:

def change_onwind_cf(n,i):
    
    onwind_gen = n.generators[n.generators.carrier.str.contains("onwind", case=False, na=False)].index
    for g in onwind_gen:
        n.generators_t.p_max_pu[g] = onwind_cf[choice[i]]


def change_offwind_cf(n, i):
    offwind_gen = n.generators[n.generators.carrier.str.contains("offwind", case=False, na=False)].index
    for g in offwind_gen:
        n.generators_t.p_max_pu[g] = offwind_cf[choice[i]]


def change_solar_cf(n, i):
    n.generators_t.p_max_pu['DE0 0 solar-2035'] = solar_cf[choice[i]]
    n.generators_t.p_max_pu['DE0 0 solar-2020'] = solar_cf[choice[i]]
    n.generators_t.p_max_pu['DE0 0 solar-2005'] = solar_cf[choice[i]]
    n.generators_t.p_max_pu['DE0 0 solar-2015'] = solar_cf[choice[i]]
    n.generators_t.p_max_pu['DE0 0 solar-2010'] = solar_cf[choice[i]]

historic wind data mit biomass und rolling horizon

In [24]:
n_rh_with_biomass = n_lt.copy()
add_carbon_price(n_rh_with_biomass, co2_prices["2035"], specific_emissions_biomass)
build_st_network(n_rh_with_biomass)

n_rh_with_biomass.optimize.optimize_with_rolling_horizon(
    horizon = horizon,
    overlap = 0,
    solver_name='gurobi'
)

WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-01 00:00:00:2019-01-06 21:00:00] (1/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 98.47it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 256.88it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hjhr27qh.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hjhr27qh.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x867715dd

INFO:gurobipy:Model fingerprint: 0x867715dd

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3338 columns

INFO:gurobipy:Presolve removed 23612 rows and 3338 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1205 rows, 8710 columns, 17257 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8710 columns, 17257 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.315e+03

INFO:gurobipy: AA' NZ     : 3.315e+03

 Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

 Factor Ops : 1.100e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.100e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.53822789e+11 -2.89284254e+12  6.49e+05 8.70e+01  1.48e+09     0s

INFO:gurobipy:   0   1.53822789e+11 -2.89284254e+12  6.49e+05 8.70e+01  1.48e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1633    1.9815240e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1633    1.9815240e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1633 iterations and 0.08 seconds (0.05 work units)

INFO:gurobipy:Solved in 1633 iterations and 0.08 seconds (0.05 work units)

Optimal objective  1.981524008e+09

INFO:gurobipy:Optimal objective  1.981524008e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.98e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-07 00:00:00:2019-01-12 21:00:00] (2/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.01it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.14it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qg8kxi92.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qg8kxi92.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc0f5ccf6

INFO:gurobipy:Model fingerprint: 0xc0f5ccf6

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3336 columns

INFO:gurobipy:Presolve removed 23612 rows and 3336 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1205 rows, 8712 columns, 17259 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8712 columns, 17259 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.315e+03

INFO:gurobipy: AA' NZ     : 3.315e+03

 Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

 Factor Ops : 1.100e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.100e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.56972962e+11 -2.91093585e+12  6.61e+05 8.99e+01  1.51e+09     0s

INFO:gurobipy:   0   1.56972962e+11 -2.91093585e+12  6.61e+05 8.99e+01  1.51e+09     0s

   1   1.73309688e+10 -5.75066442e+11  3.32e+04 4.72e-11  9.68e+07     0s

INFO:gurobipy:   1   1.73309688e+10 -5.75066442e+11  3.32e+04 4.72e-11  9.68e+07     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1755    2.0368435e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1755    2.0368435e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1755 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1755 iterations and 0.09 seconds (0.05 work units)

Optimal objective  2.036843458e+09

INFO:gurobipy:Optimal objective  2.036843458e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.04e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-13 00:00:00:2019-01-18 21:00:00] (3/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.26it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.81it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-736jvddp.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-736jvddp.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xa9ad4ecc

INFO:gurobipy:Model fingerprint: 0xa9ad4ecc

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3339 columns

INFO:gurobipy:Presolve removed 23613 rows and 3339 columns

Presolve time: 0.14s

INFO:gurobipy:Presolve time: 0.14s

Presolved: 1204 rows, 8709 columns, 17255 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8709 columns, 17255 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.41777842e+11 -2.91932167e+12  5.94e+05 9.44e+01  1.37e+09     0s

INFO:gurobipy:   0   1.41777842e+11 -2.91932167e+12  5.94e+05 9.44e+01  1.37e+09     0s

   1   1.67512314e+10 -5.51668024e+11  3.23e+04 5.43e-11  9.35e+07     0s

INFO:gurobipy:   1   1.67512314e+10 -5.51668024e+11  3.23e+04 5.43e-11  9.35e+07     0s

   2   6.15150741e+09 -1.33626184e+11  3.11e+03 1.42e-10  1.26e+07     0s

INFO:gurobipy:   2   6.15150741e+09 -1.33626184e+11  3.11e+03 1.42e-10  1.26e+07     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.17 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.17 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1796    1.6493106e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1796    1.6493106e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1796 iterations and 0.20 seconds (0.05 work units)

INFO:gurobipy:Solved in 1796 iterations and 0.20 seconds (0.05 work units)

Optimal objective  1.649310627e+09

INFO:gurobipy:Optimal objective  1.649310627e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.65e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-19 00:00:00:2019-01-24 21:00:00] (4/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.19it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.73it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-j6kne4nt.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-j6kne4nt.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xe57cc452

INFO:gurobipy:Model fingerprint: 0xe57cc452

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3444 columns

INFO:gurobipy:Presolve removed 23613 rows and 3444 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1204 rows, 8604 columns, 17130 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8604 columns, 17130 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.16366046e+11 -2.92764270e+12  1.01e+06 1.38e+02  2.21e+09     0s

INFO:gurobipy:   0   2.16366046e+11 -2.92764270e+12  1.01e+06 1.38e+02  2.21e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1522    6.3513790e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1522    6.3513790e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1522 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1522 iterations and 0.09 seconds (0.05 work units)

Optimal objective  6.351378985e+09

INFO:gurobipy:Optimal objective  6.351378985e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 6.35e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-25 00:00:00:2019-01-30 21:00:00] (5/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.02it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.16it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4rqacjg8.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4rqacjg8.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xd6c87fa3

INFO:gurobipy:Model fingerprint: 0xd6c87fa3

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3362 columns

INFO:gurobipy:Presolve removed 23611 rows and 3362 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8686 columns, 17232 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8686 columns, 17232 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.73383275e+11 -2.74295822e+12  7.50e+05 1.26e+02  1.68e+09     0s

INFO:gurobipy:   0   1.73383275e+11 -2.74295822e+12  7.50e+05 1.26e+02  1.68e+09     0s

   1   1.78306561e+10 -6.02533892e+11  3.39e+04 5.08e-11  1.00e+08     0s

INFO:gurobipy:   1   1.78306561e+10 -6.02533892e+11  3.39e+04 5.08e-11  1.00e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1787    2.5949078e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1787    2.5949078e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1787 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1787 iterations and 0.11 seconds (0.05 work units)

Optimal objective  2.594907757e+09

INFO:gurobipy:Optimal objective  2.594907757e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.59e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-31 00:00:00:2019-02-05 21:00:00] (6/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.79it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 236.00it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-377x27qd.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-377x27qd.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x28cf170d

INFO:gurobipy:Model fingerprint: 0x28cf170d

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3320 columns

INFO:gurobipy:Presolve removed 23611 rows and 3320 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8728 columns, 17276 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8728 columns, 17276 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.84174515e+11 -2.74181043e+12  7.95e+05 8.48e+01  1.77e+09     0s

INFO:gurobipy:   0   1.84174515e+11 -2.74181043e+12  7.95e+05 8.48e+01  1.77e+09     0s

   1   1.81975287e+10 -6.15960620e+11  3.47e+04 4.66e-11  1.03e+08     0s

INFO:gurobipy:   1   1.81975287e+10 -6.15960620e+11  3.47e+04 4.66e-11  1.03e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1648    2.8791187e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1648    2.8791187e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1648 iterations and 0.08 seconds (0.05 work units)

INFO:gurobipy:Solved in 1648 iterations and 0.08 seconds (0.05 work units)

Optimal objective  2.879118728e+09

INFO:gurobipy:Optimal objective  2.879118728e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.88e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-06 00:00:00:2019-02-11 21:00:00] (7/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 98.38it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 260.56it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ducbmrna.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ducbmrna.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x43bf1d02

INFO:gurobipy:Model fingerprint: 0x43bf1d02

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3290 columns

INFO:gurobipy:Presolve removed 23611 rows and 3290 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.09667061e+11 -2.76112885e+12  9.05e+05 8.60e+01  1.99e+09     0s

INFO:gurobipy:   0   2.09667061e+11 -2.76112885e+12  9.05e+05 8.60e+01  1.99e+09     0s

   1   1.86542125e+10 -6.74358466e+11  3.97e+04 4.62e-11  1.16e+08     0s

INFO:gurobipy:   1   1.86542125e+10 -6.74358466e+11  3.97e+04 4.62e-11  1.16e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1688    1.5080164e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1688    1.5080164e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1688 iterations and 0.08 seconds (0.05 work units)

INFO:gurobipy:Solved in 1688 iterations and 0.08 seconds (0.05 work units)

Optimal objective  1.508016421e+09

INFO:gurobipy:Optimal objective  1.508016421e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.51e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-12 00:00:00:2019-02-17 21:00:00] (8/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 98.45it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 257.43it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-derlpu0w.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-derlpu0w.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0ca7d95e

INFO:gurobipy:Model fingerprint: 0x0ca7d95e

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3275 columns

INFO:gurobipy:Presolve removed 23611 rows and 3275 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1206 rows, 8773 columns, 17321 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8773 columns, 17321 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.42376918e+11 -2.84062910e+12  1.06e+06 8.26e+01  2.30e+09     0s

INFO:gurobipy:   0   2.42376918e+11 -2.84062910e+12  1.06e+06 8.26e+01  2.30e+09     0s

   1   2.06916780e+10 -7.24622667e+11  4.69e+04 5.11e-11  1.33e+08     0s

INFO:gurobipy:   1   2.06916780e+10 -7.24622667e+11  4.69e+04 5.11e-11  1.33e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1654    1.8289554e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1654    1.8289554e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1654 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1654 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.828955360e+09

INFO:gurobipy:Optimal objective  1.828955360e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.83e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-18 00:00:00:2019-02-23 21:00:00] (9/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.71it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 246.40it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-9s2e99uk.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-9s2e99uk.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x5ce34e03

INFO:gurobipy:Model fingerprint: 0x5ce34e03

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3275 columns

INFO:gurobipy:Presolve removed 23611 rows and 3275 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1206 rows, 8773 columns, 17321 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8773 columns, 17321 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.40090617e+11 -2.81647934e+12  1.04e+06 8.30e+01  2.28e+09     0s

INFO:gurobipy:   0   2.40090617e+11 -2.81647934e+12  1.04e+06 8.30e+01  2.28e+09     0s

   1   2.05704016e+10 -7.18740120e+11  4.63e+04 5.16e-11  1.31e+08     0s

INFO:gurobipy:   1   2.05704016e+10 -7.18740120e+11  4.63e+04 5.16e-11  1.31e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1640    1.8823029e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1640    1.8823029e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1640 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1640 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.882302877e+09

INFO:gurobipy:Optimal objective  1.882302877e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.88e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-24 00:00:00:2019-03-01 21:00:00] (10/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 98.16it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 259.61it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6_rp7agg.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6_rp7agg.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0359eb18

INFO:gurobipy:Model fingerprint: 0x0359eb18

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3290 columns

INFO:gurobipy:Presolve removed 23611 rows and 3290 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.52611408e+11 -2.78034327e+12  1.11e+06 9.77e+01  2.40e+09     0s

INFO:gurobipy:   0   2.52611408e+11 -2.78034327e+12  1.11e+06 9.77e+01  2.40e+09     0s

   1   2.13033887e+10 -7.30412549e+11  4.94e+04 5.44e-11  1.38e+08     0s

INFO:gurobipy:   1   2.13033887e+10 -7.30412549e+11  4.94e+04 5.44e-11  1.38e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1524    2.0510585e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1524    2.0510585e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1524 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1524 iterations and 0.10 seconds (0.05 work units)

Optimal objective  2.051058455e+09

INFO:gurobipy:Optimal objective  2.051058455e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.05e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-02 00:00:00:2019-03-07 21:00:00] (11/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.31it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.40it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-xc5qhwh9.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-xc5qhwh9.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x356973f4

INFO:gurobipy:Model fingerprint: 0x356973f4

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3281 columns

INFO:gurobipy:Presolve removed 23611 rows and 3281 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8767 columns, 17315 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8767 columns, 17315 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.69084533e+11 -2.77267364e+12  1.19e+06 8.28e+01  2.56e+09     0s

INFO:gurobipy:   0   2.69084533e+11 -2.77267364e+12  1.19e+06 8.28e+01  2.56e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1587    1.1895295e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1587    1.1895295e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1587 iterations and 0.08 seconds (0.05 work units)

INFO:gurobipy:Solved in 1587 iterations and 0.08 seconds (0.05 work units)

Optimal objective  1.189529527e+09

INFO:gurobipy:Optimal objective  1.189529527e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.19e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-08 00:00:00:2019-03-13 21:00:00] (12/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 93.81it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 257.24it/s]
INFO:linopy.io: Writing time: 0.32s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nsyvjzho.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nsyvjzho.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc61bd95d

INFO:gurobipy:Model fingerprint: 0xc61bd95d

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 4e+02]

INFO:gurobipy:  Bounds range     [4e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3276 columns

INFO:gurobipy:Presolve removed 23612 rows and 3276 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1205 rows, 8772 columns, 17319 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8772 columns, 17319 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.315e+03

INFO:gurobipy: AA' NZ     : 3.315e+03

 Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

 Factor Ops : 1.100e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.100e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.80360608e+11 -2.91394913e+12  1.23e+06 8.29e+01  2.66e+09     0s

INFO:gurobipy:   0   2.80360608e+11 -2.91394913e+12  1.23e+06 8.29e+01  2.66e+09     0s

   1   2.21324712e+10 -7.99957765e+11  5.48e+04 5.32e-11  1.53e+08     0s

INFO:gurobipy:   1   2.21324712e+10 -7.99957765e+11  5.48e+04 5.32e-11  1.53e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1653    1.2229247e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1653    1.2229247e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1653 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1653 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.222924668e+09

INFO:gurobipy:Optimal objective  1.222924668e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.22e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-14 00:00:00:2019-03-19 21:00:00] (13/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 91.59it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 259.18it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-77g2ox29.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-77g2ox29.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x31ea797e

INFO:gurobipy:Model fingerprint: 0x31ea797e

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 6e+02]

INFO:gurobipy:  Bounds range     [4e+02, 6e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3279 columns

INFO:gurobipy:Presolve removed 23614 rows and 3279 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1203 rows, 8769 columns, 17314 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8769 columns, 17314 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.313e+03

INFO:gurobipy: AA' NZ     : 3.313e+03

 Factor NZ  : 2.756e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.756e+04 (roughly 4 MB of memory)

 Factor Ops : 9.118e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.118e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.92142074e+11 -3.01620046e+12  1.29e+06 8.29e+01  2.78e+09     0s

INFO:gurobipy:   0   2.92142074e+11 -3.01620046e+12  1.29e+06 8.29e+01  2.78e+09     0s

   1   2.28036434e+10 -8.12814854e+11  5.74e+04 5.30e-11  1.59e+08     0s

INFO:gurobipy:   1   2.28036434e+10 -8.12814854e+11  5.74e+04 5.30e-11  1.59e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1615    1.2442871e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1615    1.2442871e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1615 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1615 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.244287070e+09

INFO:gurobipy:Optimal objective  1.244287070e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.24e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-20 00:00:00:2019-03-25 21:00:00] (14/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.03it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.47it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x56eizps.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x56eizps.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xf3219c59

INFO:gurobipy:Model fingerprint: 0xf3219c59

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 7e+02]

INFO:gurobipy:  Bounds range     [5e+02, 7e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23616 rows and 3298 columns

INFO:gurobipy:Presolve removed 23616 rows and 3298 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1201 rows, 8750 columns, 17293 nonzeros

INFO:gurobipy:Presolved: 1201 rows, 8750 columns, 17293 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.311e+03

INFO:gurobipy: AA' NZ     : 3.311e+03

 Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

 Factor Ops : 1.072e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.072e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.04558263e+11 -3.10495524e+12  1.35e+06 1.05e+02  2.91e+09     0s

INFO:gurobipy:   0   3.04558263e+11 -3.10495524e+12  1.35e+06 1.05e+02  2.91e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1495    1.5630503e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1495    1.5630503e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1495 iterations and 0.18 seconds (0.05 work units)

INFO:gurobipy:Solved in 1495 iterations and 0.18 seconds (0.05 work units)

Optimal objective  1.563050316e+09

INFO:gurobipy:Optimal objective  1.563050316e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.56e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-26 00:00:00:2019-03-31 21:00:00] (15/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.66it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.48it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nefhanbj.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nefhanbj.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x3619ec83

INFO:gurobipy:Model fingerprint: 0x3619ec83

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 5e+02]

INFO:gurobipy:  Bounds range     [5e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23615 rows and 3286 columns

INFO:gurobipy:Presolve removed 23615 rows and 3286 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1202 rows, 8762 columns, 17306 nonzeros

INFO:gurobipy:Presolved: 1202 rows, 8762 columns, 17306 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.312e+03

INFO:gurobipy: AA' NZ     : 3.312e+03

 Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

 Factor Ops : 9.564e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.564e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.25101315e+11 -3.08873033e+12  1.45e+06 8.24e+01  3.11e+09     0s

INFO:gurobipy:   0   3.25101315e+11 -3.08873033e+12  1.45e+06 8.24e+01  3.11e+09     0s

   1   3.45321814e+10 -8.40548842e+11  1.09e+05 5.44e-11  2.62e+08     0s

INFO:gurobipy:   1   3.45321814e+10 -8.40548842e+11  1.09e+05 5.44e-11  2.62e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1566    1.6390941e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1566    1.6390941e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1566 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1566 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.639094069e+09

INFO:gurobipy:Optimal objective  1.639094069e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.64e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-01 00:00:00:2019-04-06 21:00:00] (16/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.81it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.99it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fuv6v81o.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fuv6v81o.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x2600b316

INFO:gurobipy:Model fingerprint: 0x2600b316

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 5e+02]

INFO:gurobipy:  Bounds range     [4e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23615 rows and 3280 columns

INFO:gurobipy:Presolve removed 23615 rows and 3280 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1202 rows, 8768 columns, 17312 nonzeros

INFO:gurobipy:Presolved: 1202 rows, 8768 columns, 17312 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.312e+03

INFO:gurobipy: AA' NZ     : 3.312e+03

 Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

 Factor Ops : 9.564e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.564e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.69087104e+11 -3.10536359e+12  1.66e+06 8.04e+01  3.55e+09     0s

INFO:gurobipy:   0   3.69087104e+11 -3.10536359e+12  1.66e+06 8.04e+01  3.55e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1424    1.7968710e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1424    1.7968710e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1424 iterations and 0.13 seconds (0.04 work units)

INFO:gurobipy:Solved in 1424 iterations and 0.13 seconds (0.04 work units)

Optimal objective  1.796870964e+09

INFO:gurobipy:Optimal objective  1.796870964e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.80e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-07 00:00:00:2019-04-12 21:00:00] (17/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.86it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 258.39it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7gc5qng7.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7gc5qng7.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x15a0d426

INFO:gurobipy:Model fingerprint: 0x15a0d426

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 5e+02]

INFO:gurobipy:  Bounds range     [5e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23615 rows and 3269 columns

INFO:gurobipy:Presolve removed 23615 rows and 3269 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1202 rows, 8779 columns, 17323 nonzeros

INFO:gurobipy:Presolved: 1202 rows, 8779 columns, 17323 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.312e+03

INFO:gurobipy: AA' NZ     : 3.312e+03

 Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

 Factor Ops : 9.564e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.564e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.76325482e+11 -3.09757881e+12  1.70e+06 8.21e+01  3.62e+09     0s

INFO:gurobipy:   0   3.76325482e+11 -3.09757881e+12  1.70e+06 8.21e+01  3.62e+09     0s

   1   4.40192484e+10 -9.20336895e+11  1.52e+05 5.35e-11  3.52e+08     0s

INFO:gurobipy:   1   4.40192484e+10 -9.20336895e+11  1.52e+05 5.35e-11  3.52e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1596    1.7036525e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1596    1.7036525e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1596 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1596 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.703652531e+09

INFO:gurobipy:Optimal objective  1.703652531e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.70e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-13 00:00:00:2019-04-18 21:00:00] (18/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 91.35it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 256.27it/s]
INFO:linopy.io: Writing time: 0.33s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_fwi4e90.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_fwi4e90.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xab380d0a

INFO:gurobipy:Model fingerprint: 0xab380d0a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 5e+02]

INFO:gurobipy:  Bounds range     [4e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23615 rows and 3285 columns

INFO:gurobipy:Presolve removed 23615 rows and 3285 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1202 rows, 8763 columns, 17295 nonzeros

INFO:gurobipy:Presolved: 1202 rows, 8763 columns, 17295 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.312e+03

INFO:gurobipy: AA' NZ     : 3.312e+03

 Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.814e+04 (roughly 4 MB of memory)

 Factor Ops : 9.564e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.564e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.38983011e+11 -3.08737886e+12  1.06e+06 1.58e+03  2.32e+09     0s

INFO:gurobipy:   0   2.38983011e+11 -3.08737886e+12  1.06e+06 1.58e+03  2.32e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1603    1.2626097e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1603    1.2626097e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1603 iterations and 0.14 seconds (0.04 work units)

INFO:gurobipy:Solved in 1603 iterations and 0.14 seconds (0.04 work units)

Optimal objective  1.262609690e+09

INFO:gurobipy:Optimal objective  1.262609690e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.26e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-19 00:00:00:2019-04-24 21:00:00] (19/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 93.27it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.25it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-44augj7g.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-44augj7g.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x60acde03

INFO:gurobipy:Model fingerprint: 0x60acde03

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23616 rows and 3436 columns

INFO:gurobipy:Presolve removed 23616 rows and 3436 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1201 rows, 8612 columns, 17023 nonzeros

INFO:gurobipy:Presolved: 1201 rows, 8612 columns, 17023 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.311e+03

INFO:gurobipy: AA' NZ     : 3.311e+03

 Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

 Factor Ops : 1.072e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.072e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.39032366e+11 -3.15939477e+12  1.09e+06 1.64e+03  2.38e+09     0s

INFO:gurobipy:   0   2.39032366e+11 -3.15939477e+12  1.09e+06 1.64e+03  2.38e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1434    1.0476773e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1434    1.0476773e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1434 iterations and 0.08 seconds (0.04 work units)

INFO:gurobipy:Solved in 1434 iterations and 0.08 seconds (0.04 work units)

Optimal objective  1.047677334e+09

INFO:gurobipy:Optimal objective  1.047677334e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.05e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-25 00:00:00:2019-04-30 21:00:00] (20/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 80.97it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 207.78it/s]
INFO:linopy.io: Writing time: 0.32s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_lq7mfii.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_lq7mfii.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x3780ecbb

INFO:gurobipy:Model fingerprint: 0x3780ecbb

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3322 columns

INFO:gurobipy:Presolve removed 23619 rows and 3322 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1198 rows, 8726 columns, 17226 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8726 columns, 17226 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.308e+03

INFO:gurobipy: AA' NZ     : 3.308e+03

 Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

 Factor Ops : 1.046e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.046e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.82009023e+11 -3.27592882e+12  1.27e+06 1.61e+03  2.75e+09     0s

INFO:gurobipy:   0   2.82009023e+11 -3.27592882e+12  1.27e+06 1.61e+03  2.75e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1627    1.4597231e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1627    1.4597231e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1627 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1627 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.459723147e+09

INFO:gurobipy:Optimal objective  1.459723147e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.46e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-01 00:00:00:2019-05-06 21:00:00] (21/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.91it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 245.22it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4ka_o74n.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4ka_o74n.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x6dcd460a

INFO:gurobipy:Model fingerprint: 0x6dcd460a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3257 columns

INFO:gurobipy:Presolve removed 23619 rows and 3257 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1198 rows, 8791 columns, 17331 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8791 columns, 17331 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.308e+03

INFO:gurobipy: AA' NZ     : 3.308e+03

 Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

 Factor Ops : 1.046e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.046e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.87195681e+11 -3.29914562e+12  1.28e+06 7.51e+01  2.78e+09     0s

INFO:gurobipy:   0   2.87195681e+11 -3.29914562e+12  1.28e+06 7.51e+01  2.78e+09     0s

   1   3.16756352e+10 -7.81258850e+11  9.78e+04 5.22e-11  2.36e+08     0s

INFO:gurobipy:   1   3.16756352e+10 -7.81258850e+11  9.78e+04 5.22e-11  2.36e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1612    1.3751647e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1612    1.3751647e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1612 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1612 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.375164664e+09

INFO:gurobipy:Optimal objective  1.375164664e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.38e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-07 00:00:00:2019-05-12 21:00:00] (22/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.91it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.92it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-k3nsc0rp.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-k3nsc0rp.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x1c80d04e

INFO:gurobipy:Model fingerprint: 0x1c80d04e

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23620 rows and 3252 columns

INFO:gurobipy:Presolve removed 23620 rows and 3252 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1197 rows, 8796 columns, 17335 nonzeros

INFO:gurobipy:Presolved: 1197 rows, 8796 columns, 17335 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.307e+03

INFO:gurobipy: AA' NZ     : 3.307e+03

 Factor NZ  : 2.828e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.828e+04 (roughly 4 MB of memory)

 Factor Ops : 1.009e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.009e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   4.34109139e+11 -3.33083878e+12  1.98e+06 8.49e+01  4.20e+09     0s

INFO:gurobipy:   0   4.34109139e+11 -3.33083878e+12  1.98e+06 8.49e+01  4.20e+09     0s

   1   4.33078194e+10 -9.83856499e+11  1.48e+05 4.84e-11  3.48e+08     0s

INFO:gurobipy:   1   4.33078194e+10 -9.83856499e+11  1.48e+05 4.84e-11  3.48e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1661    1.4743450e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1661    1.4743450e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1661 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1661 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.474344952e+09

INFO:gurobipy:Optimal objective  1.474344952e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.47e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-13 00:00:00:2019-05-18 21:00:00] (23/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.72it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 232.25it/s]
INFO:linopy.io: Writing time: 0.32s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3f54opuu.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3f54opuu.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x7691d9e0

INFO:gurobipy:Model fingerprint: 0x7691d9e0

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3270 columns

INFO:gurobipy:Presolve removed 23619 rows and 3270 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1198 rows, 8778 columns, 17287 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8778 columns, 17287 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.308e+03

INFO:gurobipy: AA' NZ     : 3.308e+03

 Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

 Factor Ops : 1.046e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.046e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.02891800e+11 -3.32305312e+12  1.36e+06 1.61e+03  2.95e+09     0s

INFO:gurobipy:   0   3.02891800e+11 -3.32305312e+12  1.36e+06 1.61e+03  2.95e+09     0s

   1   3.80785136e+10 -8.00678180e+11  1.28e+05 5.44e-11  2.95e+08     0s

INFO:gurobipy:   1   3.80785136e+10 -8.00678180e+11  1.28e+05 5.44e-11  2.95e+08     0s

   2   7.75133586e+09 -2.39530268e+11  6.61e+03 7.39e-11  2.53e+07     0s

INFO:gurobipy:   2   7.75133586e+09 -2.39530268e+11  6.61e+03 7.39e-11  2.53e+07     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1676    1.3842880e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1676    1.3842880e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1676 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1676 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.384287974e+09

INFO:gurobipy:Optimal objective  1.384287974e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.38e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-19 00:00:00:2019-05-24 21:00:00] (24/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 90.10it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.28it/s]
INFO:linopy.io: Writing time: 0.34s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-h4ied0zb.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-h4ied0zb.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x061118ea

INFO:gurobipy:Model fingerprint: 0x061118ea

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 5e+02]

INFO:gurobipy:  Bounds range     [2e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3391 columns

INFO:gurobipy:Presolve removed 23619 rows and 3391 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1198 rows, 8657 columns, 17072 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8657 columns, 17072 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.308e+03

INFO:gurobipy: AA' NZ     : 3.308e+03

 Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.849e+04 (roughly 4 MB of memory)

 Factor Ops : 1.046e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.046e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.74799499e+11 -3.30782397e+12  1.27e+06 1.58e+03  2.73e+09     0s

INFO:gurobipy:   0   2.74799499e+11 -3.30782397e+12  1.27e+06 1.58e+03  2.73e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1457    1.1413114e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1457    1.1413114e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1457 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1457 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.141311388e+09

INFO:gurobipy:Optimal objective  1.141311388e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.14e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-25 00:00:00:2019-05-30 21:00:00] (25/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.60it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.86it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-l3bps13a.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-l3bps13a.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xe6458d40

INFO:gurobipy:Model fingerprint: 0xe6458d40

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 5e+02]

INFO:gurobipy:  Bounds range     [3e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23618 rows and 3373 columns

INFO:gurobipy:Presolve removed 23618 rows and 3373 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1199 rows, 8675 columns, 20127 nonzeros

INFO:gurobipy:Presolved: 1199 rows, 8675 columns, 20127 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.931e+03

INFO:gurobipy: AA' NZ     : 3.931e+03

 Factor NZ  : 2.903e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.903e+04 (roughly 4 MB of memory)

 Factor Ops : 1.070e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.070e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.50583170e+13 -4.84878343e+12  9.09e+08 1.55e+03  1.47e+11     0s

INFO:gurobipy:   0   1.50583170e+13 -4.84878343e+12  9.09e+08 1.55e+03  1.47e+11     0s

   1   1.45609874e+12 -3.76000405e+12  8.36e+07 1.30e+04  1.38e+10     0s

INFO:gurobipy:   1   1.45609874e+12 -3.76000405e+12  8.36e+07 1.30e+04  1.38e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1487    1.1714170e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1487    1.1714170e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1487 iterations and 0.11 seconds (0.06 work units)

INFO:gurobipy:Solved in 1487 iterations and 0.11 seconds (0.06 work units)

Optimal objective  1.171416968e+09

INFO:gurobipy:Optimal objective  1.171416968e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.17e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-31 00:00:00:2019-06-05 21:00:00] (26/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 91.32it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.75it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-pymu62ng.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-pymu62ng.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xba881e09

INFO:gurobipy:Model fingerprint: 0xba881e09

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3499 columns

INFO:gurobipy:Presolve removed 23619 rows and 3499 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1198 rows, 8549 columns, 19882 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8549 columns, 19882 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.930e+03

INFO:gurobipy: AA' NZ     : 3.930e+03

 Factor NZ  : 2.754e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.754e+04 (roughly 4 MB of memory)

 Factor Ops : 9.031e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.031e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.79715416e+13 -4.89443151e+12  6.44e+08 1.81e+03  1.74e+11     0s

INFO:gurobipy:   0   1.79715416e+13 -4.89443151e+12  6.44e+08 1.81e+03  1.74e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1475    1.0910421e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1475    1.0910421e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1475 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1475 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.091042072e+09

INFO:gurobipy:Optimal objective  1.091042072e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.09e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-06 00:00:00:2019-06-11 21:00:00] (27/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.55it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.12it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hul4o_eb.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hul4o_eb.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x7e900c8c

INFO:gurobipy:Model fingerprint: 0x7e900c8c

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23621 rows and 3503 columns

INFO:gurobipy:Presolve removed 23621 rows and 3503 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1196 rows, 8545 columns, 19876 nonzeros

INFO:gurobipy:Presolved: 1196 rows, 8545 columns, 19876 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.926e+03

INFO:gurobipy: AA' NZ     : 3.926e+03

 Factor NZ  : 2.963e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.963e+04 (roughly 4 MB of memory)

 Factor Ops : 1.148e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.148e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.83690661e+13 -4.97215288e+12  5.38e+08 1.65e+03  1.78e+11     0s

INFO:gurobipy:   0   1.83690661e+13 -4.97215288e+12  5.38e+08 1.65e+03  1.78e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1524    1.1116791e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1524    1.1116791e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1524 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1524 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.111679100e+09

INFO:gurobipy:Optimal objective  1.111679100e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.11e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-12 00:00:00:2019-06-17 21:00:00] (28/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.19it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 240.78it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nh2_g5ba.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nh2_g5ba.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x378d901a

INFO:gurobipy:Model fingerprint: 0x378d901a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23623 rows and 3567 columns

INFO:gurobipy:Presolve removed 23623 rows and 3567 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1194 rows, 8481 columns, 19742 nonzeros

INFO:gurobipy:Presolved: 1194 rows, 8481 columns, 19742 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.922e+03

INFO:gurobipy: AA' NZ     : 3.922e+03

 Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

 Factor Ops : 1.082e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.082e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.85866527e+13 -4.98555793e+12  5.45e+08 1.75e+03  1.79e+11     0s

INFO:gurobipy:   0   1.85866527e+13 -4.98555793e+12  5.45e+08 1.75e+03  1.79e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1564    1.1062886e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1564    1.1062886e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1564 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1564 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.106288621e+09

INFO:gurobipy:Optimal objective  1.106288621e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.11e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-18 00:00:00:2019-06-23 21:00:00] (29/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.47it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 251.81it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5iyoqmkl.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5iyoqmkl.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x596cad9a

INFO:gurobipy:Model fingerprint: 0x596cad9a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23624 rows and 3590 columns

INFO:gurobipy:Presolve removed 23624 rows and 3590 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1193 rows, 8458 columns, 19690 nonzeros

INFO:gurobipy:Presolved: 1193 rows, 8458 columns, 19690 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.920e+03

INFO:gurobipy: AA' NZ     : 3.920e+03

 Factor NZ  : 2.724e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.724e+04 (roughly 4 MB of memory)

 Factor Ops : 9.167e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.167e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.88143453e+13 -5.03196135e+12  5.51e+08 1.80e+03  1.81e+11     0s

INFO:gurobipy:   0   1.88143453e+13 -5.03196135e+12  5.51e+08 1.80e+03  1.81e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1538    1.1754963e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1538    1.1754963e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1538 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1538 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.175496284e+09

INFO:gurobipy:Optimal objective  1.175496284e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.18e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-24 00:00:00:2019-06-29 21:00:00] (30/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.55it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.03it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-vytpn8un.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-vytpn8un.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xdb139fd5

INFO:gurobipy:Model fingerprint: 0xdb139fd5

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23625 rows and 3591 columns

INFO:gurobipy:Presolve removed 23625 rows and 3591 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1192 rows, 8457 columns, 19688 nonzeros

INFO:gurobipy:Presolved: 1192 rows, 8457 columns, 19688 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.918e+03

INFO:gurobipy: AA' NZ     : 3.918e+03

 Factor NZ  : 2.866e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.866e+04 (roughly 4 MB of memory)

 Factor Ops : 1.036e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.036e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.91728233e+13 -5.07764862e+12  5.62e+08 1.82e+03  1.85e+11     0s

INFO:gurobipy:   0   1.91728233e+13 -5.07764862e+12  5.62e+08 1.82e+03  1.85e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1460    1.1079396e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1460    1.1079396e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1460 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1460 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.107939649e+09

INFO:gurobipy:Optimal objective  1.107939649e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.11e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-30 00:00:00:2019-07-05 21:00:00] (31/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.46it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 260.44it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ndhfg79_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ndhfg79_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x8ca8ce58

INFO:gurobipy:Model fingerprint: 0x8ca8ce58

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23626 rows and 3586 columns

INFO:gurobipy:Presolve removed 23626 rows and 3586 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1191 rows, 8462 columns, 19698 nonzeros

INFO:gurobipy:Presolved: 1191 rows, 8462 columns, 19698 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.917e+03

INFO:gurobipy: AA' NZ     : 3.917e+03

 Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

 Factor Ops : 1.058e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.058e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.65176752e+13 -7.80120292e+12  4.84e+08 1.76e+03  1.60e+11     0s

INFO:gurobipy:   0   1.65176752e+13 -7.80120292e+12  4.84e+08 1.76e+03  1.60e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1530    1.0522845e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1530    1.0522845e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1530 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1530 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.052284453e+09

INFO:gurobipy:Optimal objective  1.052284453e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.05e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-06 00:00:00:2019-07-11 21:00:00] (32/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.60it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 255.66it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-tda_sgsi.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-tda_sgsi.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xa450777f

INFO:gurobipy:Model fingerprint: 0xa450777f

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23628 rows and 3518 columns

INFO:gurobipy:Presolve removed 23628 rows and 3518 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1189 rows, 8530 columns, 19844 nonzeros

INFO:gurobipy:Presolved: 1189 rows, 8530 columns, 19844 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.913e+03

INFO:gurobipy: AA' NZ     : 3.913e+03

 Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

 Factor Ops : 1.158e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.158e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.68072767e+13 -9.81622806e+12  4.92e+08 1.68e+03  1.63e+11     0s

INFO:gurobipy:   0   1.68072767e+13 -9.81622806e+12  4.92e+08 1.68e+03  1.63e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1436    1.2525687e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1436    1.2525687e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1436 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1436 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.252568726e+09

INFO:gurobipy:Optimal objective  1.252568726e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.25e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-12 00:00:00:2019-07-17 21:00:00] (33/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.84it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.24it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-q5mz63d7.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-q5mz63d7.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xeee0b6fc

INFO:gurobipy:Model fingerprint: 0xeee0b6fc

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23626 rows and 3620 columns

INFO:gurobipy:Presolve removed 23626 rows and 3620 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1191 rows, 8428 columns, 19658 nonzeros

INFO:gurobipy:Presolved: 1191 rows, 8428 columns, 19658 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.917e+03

INFO:gurobipy: AA' NZ     : 3.917e+03

 Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

 Factor Ops : 1.058e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.058e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.69989736e+13 -9.86749235e+12  4.98e+08 1.55e+03  1.64e+11     0s

INFO:gurobipy:   0   1.69989736e+13 -9.86749235e+12  4.98e+08 1.55e+03  1.64e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1398    1.3243988e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1398    1.3243988e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1398 iterations and 0.23 seconds (0.05 work units)

INFO:gurobipy:Solved in 1398 iterations and 0.23 seconds (0.05 work units)

Optimal objective  1.324398773e+09

INFO:gurobipy:Optimal objective  1.324398773e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.32e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-18 00:00:00:2019-07-23 21:00:00] (34/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.13it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.69it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-jt23oyzm.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-jt23oyzm.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x9b7a88a1

INFO:gurobipy:Model fingerprint: 0x9b7a88a1

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23626 rows and 3617 columns

INFO:gurobipy:Presolve removed 23626 rows and 3617 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1191 rows, 8431 columns, 19661 nonzeros

INFO:gurobipy:Presolved: 1191 rows, 8431 columns, 19661 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.917e+03

INFO:gurobipy: AA' NZ     : 3.917e+03

 Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.854e+04 (roughly 4 MB of memory)

 Factor Ops : 1.058e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.058e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.71976777e+13 -9.87720476e+12  5.04e+08 1.81e+03  1.66e+11     0s

INFO:gurobipy:   0   1.71976777e+13 -9.87720476e+12  5.04e+08 1.81e+03  1.66e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1478    1.1996590e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1478    1.1996590e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1478 iterations and 0.23 seconds (0.05 work units)

INFO:gurobipy:Solved in 1478 iterations and 0.23 seconds (0.05 work units)

Optimal objective  1.199659014e+09

INFO:gurobipy:Optimal objective  1.199659014e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.20e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-24 00:00:00:2019-07-29 21:00:00] (35/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.13it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 249.49it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-uzmyeaai.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-uzmyeaai.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x49556a60

INFO:gurobipy:Model fingerprint: 0x49556a60

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23623 rows and 3598 columns

INFO:gurobipy:Presolve removed 23623 rows and 3598 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1194 rows, 8450 columns, 19683 nonzeros

INFO:gurobipy:Presolved: 1194 rows, 8450 columns, 19683 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.922e+03

INFO:gurobipy: AA' NZ     : 3.922e+03

 Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

 Factor Ops : 1.082e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.082e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.06408062e+13 -8.48999138e+12  6.05e+08 1.76e+03  1.99e+11     0s

INFO:gurobipy:   0   2.06408062e+13 -8.48999138e+12  6.05e+08 1.76e+03  1.99e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1542    1.1623517e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1542    1.1623517e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1542 iterations and 0.24 seconds (0.05 work units)

INFO:gurobipy:Solved in 1542 iterations and 0.24 seconds (0.05 work units)

Optimal objective  1.162351744e+09

INFO:gurobipy:Optimal objective  1.162351744e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.16e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-30 00:00:00:2019-08-04 21:00:00] (36/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 96.40it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 245.30it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-raivic2m.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-raivic2m.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xdf6e6d46

INFO:gurobipy:Model fingerprint: 0xdf6e6d46

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23620 rows and 3619 columns

INFO:gurobipy:Presolve removed 23620 rows and 3619 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1197 rows, 8429 columns, 19665 nonzeros

INFO:gurobipy:Presolved: 1197 rows, 8429 columns, 19665 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.928e+03

INFO:gurobipy: AA' NZ     : 3.928e+03

 Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

 Factor Ops : 1.217e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.217e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.10102606e+13 -8.53118303e+12  6.16e+08 1.76e+03  2.03e+11     0s

INFO:gurobipy:   0   2.10102606e+13 -8.53118303e+12  6.16e+08 1.76e+03  2.03e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1440    1.4406061e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1440    1.4406061e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1440 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1440 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.440606114e+09

INFO:gurobipy:Optimal objective  1.440606114e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.44e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-05 00:00:00:2019-08-10 21:00:00] (37/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.94it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 256.44it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-b6nmqmg5.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-b6nmqmg5.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x4ccd9ef5

INFO:gurobipy:Model fingerprint: 0x4ccd9ef5

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23620 rows and 3622 columns

INFO:gurobipy:Presolve removed 23620 rows and 3622 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1197 rows, 8426 columns, 19662 nonzeros

INFO:gurobipy:Presolved: 1197 rows, 8426 columns, 19662 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.928e+03

INFO:gurobipy: AA' NZ     : 3.928e+03

 Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

 Factor Ops : 1.217e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.217e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1492    1.1727885e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1492    1.1727885e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1492 iterations and 0.16 seconds (0.05 work units)

INFO:gurobipy:Solved in 1492 iterations and 0.16 seconds (0.05 work units)

Optimal objective  1.172788540e+09

INFO:gurobipy:Optimal objective  1.172788540e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.17e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-11 00:00:00:2019-08-16 21:00:00] (38/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.70it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 256.34it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-c_yzp09v.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-c_yzp09v.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x583a25a0

INFO:gurobipy:Model fingerprint: 0x583a25a0

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23619 rows and 3639 columns

INFO:gurobipy:Presolve removed 23619 rows and 3639 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1198 rows, 8409 columns, 19646 nonzeros

INFO:gurobipy:Presolved: 1198 rows, 8409 columns, 19646 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.930e+03

INFO:gurobipy: AA' NZ     : 3.930e+03

 Factor NZ  : 2.855e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.855e+04 (roughly 4 MB of memory)

 Factor Ops : 1.003e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.003e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.79851202e+13 -1.00113680e+13  5.27e+08 1.72e+03  1.74e+11     0s

INFO:gurobipy:   0   1.79851202e+13 -1.00113680e+13  5.27e+08 1.72e+03  1.74e+11     0s

   1   1.77976700e+12 -7.63075727e+12  5.37e+07 1.27e+04  1.84e+10     0s

INFO:gurobipy:   1   1.77976700e+12 -7.63075727e+12  5.37e+07 1.27e+04  1.84e+10     0s

   2   1.40434566e+11 -2.49201286e+12  3.83e+06 5.67e-11  1.43e+09     0s

INFO:gurobipy:   2   1.40434566e+11 -2.49201286e+12  3.83e+06 5.67e-11  1.43e+09     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.08 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.08 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1602    1.0861077e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1602    1.0861077e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1602 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1602 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.086107740e+09

INFO:gurobipy:Optimal objective  1.086107740e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.09e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-17 00:00:00:2019-08-22 21:00:00] (39/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.13it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.77it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hqy137m5.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hqy137m5.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x85e3b40b

INFO:gurobipy:Model fingerprint: 0x85e3b40b

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23615 rows and 3635 columns

INFO:gurobipy:Presolve removed 23615 rows and 3635 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1202 rows, 8413 columns, 19654 nonzeros

INFO:gurobipy:Presolved: 1202 rows, 8413 columns, 19654 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.938e+03

INFO:gurobipy: AA' NZ     : 3.938e+03

 Factor NZ  : 2.868e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.868e+04 (roughly 4 MB of memory)

 Factor Ops : 1.030e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.030e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.18053305e+13 -8.56277968e+12  6.39e+08 1.68e+03  2.10e+11     0s

INFO:gurobipy:   0   2.18053305e+13 -8.56277968e+12  6.39e+08 1.68e+03  2.10e+11     0s

   1   2.28319845e+12 -6.74854375e+12  6.87e+07 1.39e+04  2.32e+10     0s

INFO:gurobipy:   1   2.28319845e+12 -6.74854375e+12  6.87e+07 1.39e+04  2.32e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1635    1.1265950e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1635    1.1265950e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1635 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1635 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.126595031e+09

INFO:gurobipy:Optimal objective  1.126595031e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.13e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-23 00:00:00:2019-08-28 21:00:00] (40/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.58it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 257.66it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rhx1em2j.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rhx1em2j.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x56ef77a3

INFO:gurobipy:Model fingerprint: 0x56ef77a3

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3628 columns

INFO:gurobipy:Presolve removed 23608 rows and 3628 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.83705206e+13 -1.03391995e+13  5.38e+08 1.80e+03  1.78e+11     0s

INFO:gurobipy:   0   1.83705206e+13 -1.03391995e+13  5.38e+08 1.80e+03  1.78e+11     0s

   1   2.25304327e+12 -7.89645948e+12  6.75e+07 1.24e+04  2.29e+10     0s

INFO:gurobipy:   1   2.25304327e+12 -7.89645948e+12  6.75e+07 1.24e+04  2.29e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1640    1.2509917e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1640    1.2509917e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1640 iterations and 0.11 seconds (0.06 work units)

INFO:gurobipy:Solved in 1640 iterations and 0.11 seconds (0.06 work units)

Optimal objective  1.250991705e+09

INFO:gurobipy:Optimal objective  1.250991705e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.25e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-29 00:00:00:2019-09-03 21:00:00] (41/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.96it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 246.53it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yo5sdhd_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yo5sdhd_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x2d5d7a27

INFO:gurobipy:Model fingerprint: 0x2d5d7a27

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3650 columns

INFO:gurobipy:Presolve removed 23608 rows and 3650 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8398 columns, 19646 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8398 columns, 19646 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.85701632e+13 -1.03304720e+13  5.44e+08 1.79e+03  1.79e+11     0s

INFO:gurobipy:   0   1.85701632e+13 -1.03304720e+13  5.44e+08 1.79e+03  1.79e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.16 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.16 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1632    1.1806325e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1632    1.1806325e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1632 iterations and 0.18 seconds (0.06 work units)

INFO:gurobipy:Solved in 1632 iterations and 0.18 seconds (0.06 work units)

Optimal objective  1.180632530e+09

INFO:gurobipy:Optimal objective  1.180632530e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.18e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-04 00:00:00:2019-09-09 21:00:00] (42/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.58it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 251.75it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-z_a6t512.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-z_a6t512.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0f38ed4a

INFO:gurobipy:Model fingerprint: 0x0f38ed4a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3452 columns

INFO:gurobipy:Presolve removed 23608 rows and 3452 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8596 columns, 20064 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8596 columns, 20064 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.88194056e+13 -1.03480122e+13  5.51e+08 1.64e+03  1.83e+11     0s

INFO:gurobipy:   0   1.88194056e+13 -1.03480122e+13  5.51e+08 1.64e+03  1.83e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1444    1.5431031e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1444    1.5431031e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1444 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1444 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.543103137e+09

INFO:gurobipy:Optimal objective  1.543103137e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.54e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-10 00:00:00:2019-09-15 21:00:00] (43/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.96it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.85it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-36qpcxpz.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-36qpcxpz.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x527ef606

INFO:gurobipy:Model fingerprint: 0x527ef606

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3538 columns

INFO:gurobipy:Presolve removed 23608 rows and 3538 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8510 columns, 19860 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8510 columns, 19860 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.89468759e+13 -1.03473499e+13  5.55e+08 1.63e+03  1.84e+11     0s

INFO:gurobipy:   0   1.89468759e+13 -1.03473499e+13  5.55e+08 1.63e+03  1.84e+11     0s

   1   2.01289678e+12 -7.85720229e+12  5.97e+07 1.19e+04  2.03e+10     0s

INFO:gurobipy:   1   2.01289678e+12 -7.85720229e+12  5.97e+07 1.19e+04  2.03e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1694    1.0933955e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1694    1.0933955e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1694 iterations and 0.10 seconds (0.06 work units)

INFO:gurobipy:Solved in 1694 iterations and 0.10 seconds (0.06 work units)

Optimal objective  1.093395540e+09

INFO:gurobipy:Optimal objective  1.093395540e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.09e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-16 00:00:00:2019-09-21 21:00:00] (44/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.48it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 258.98it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-0kairot4.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-0kairot4.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12042 columns, 48950 nonzeros

INFO:gurobipy:obj: 24817 rows, 12042 columns, 48950 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12042 columns and 48950 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12042 columns and 48950 nonzeros

Model fingerprint: 0xb4b75ced

INFO:gurobipy:Model fingerprint: 0xb4b75ced

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+01, 8e+01]

INFO:gurobipy:  Bounds range     [2e+01, 8e+01]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3354 columns

INFO:gurobipy:Presolve removed 23612 rows and 3354 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1205 rows, 8688 columns, 20229 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8688 columns, 20229 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.948e+03

INFO:gurobipy: AA' NZ     : 3.948e+03

 Factor NZ  : 2.842e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.842e+04 (roughly 4 MB of memory)

 Factor Ops : 1.027e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.027e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.94655151e+13 -1.03801132e+13  5.64e+08 1.63e+03  1.89e+11     0s

INFO:gurobipy:   0   1.94655151e+13 -1.03801132e+13  5.64e+08 1.63e+03  1.89e+11     0s

   1   1.95165102e+12 -7.82492631e+12  5.41e+07 1.13e+04  1.86e+10     0s

INFO:gurobipy:   1   1.95165102e+12 -7.82492631e+12  5.41e+07 1.13e+04  1.86e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1575    1.3072616e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1575    1.3072616e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1575 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1575 iterations and 0.13 seconds (0.05 work units)

Optimal objective  1.307261620e+09

INFO:gurobipy:Optimal objective  1.307261620e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12042 primals, 24817 duals
Objective: 1.31e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-22 00:00:00:2019-09-27 21:00:00] (45/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.31it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 249.41it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mwj6ts0o.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mwj6ts0o.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12041 columns, 48949 nonzeros

INFO:gurobipy:obj: 24817 rows, 12041 columns, 48949 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12041 columns and 48949 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12041 columns and 48949 nonzeros

Model fingerprint: 0x1a658e30

INFO:gurobipy:Model fingerprint: 0x1a658e30

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+01, 1e+02]

INFO:gurobipy:  Bounds range     [2e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3581 columns

INFO:gurobipy:Presolve removed 23614 rows and 3581 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8460 columns, 19786 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8460 columns, 19786 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.946e+03

INFO:gurobipy: AA' NZ     : 3.946e+03

 Factor NZ  : 2.912e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.912e+04 (roughly 4 MB of memory)

 Factor Ops : 1.036e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.036e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.94198221e+13 -1.03212044e+13  5.69e+08 1.63e+03  1.88e+11     0s

INFO:gurobipy:   0   1.94198221e+13 -1.03212044e+13  5.69e+08 1.63e+03  1.88e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1366    1.4773388e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1366    1.4773388e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1366 iterations and 0.15 seconds (0.05 work units)

INFO:gurobipy:Solved in 1366 iterations and 0.15 seconds (0.05 work units)

Optimal objective  1.477338819e+09

INFO:gurobipy:Optimal objective  1.477338819e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12041 primals, 24817 duals
Objective: 1.48e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-28 00:00:00:2019-10-03 21:00:00] (46/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.64it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 239.95it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yeeydujl.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yeeydujl.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc2629a6e

INFO:gurobipy:Model fingerprint: 0xc2629a6e

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3438 columns

INFO:gurobipy:Presolve removed 23608 rows and 3438 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8610 columns, 20063 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8610 columns, 20063 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.01s

INFO:gurobipy:Ordering time: 0.01s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.99124947e+13 -1.03398690e+13  5.78e+08 1.50e+03  1.92e+11     0s

INFO:gurobipy:   0   1.99124947e+13 -1.03398690e+13  5.78e+08 1.50e+03  1.92e+11     0s

   1   1.79581484e+12 -7.83691214e+12  5.21e+07 1.20e+04  1.79e+10     0s

INFO:gurobipy:   1   1.79581484e+12 -7.83691214e+12  5.21e+07 1.20e+04  1.79e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1622    1.1336664e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1622    1.1336664e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1622 iterations and 0.21 seconds (0.05 work units)

INFO:gurobipy:Solved in 1622 iterations and 0.21 seconds (0.05 work units)

Optimal objective  1.133666414e+09

INFO:gurobipy:Optimal objective  1.133666414e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.13e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-04 00:00:00:2019-10-09 21:00:00] (47/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.10it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 249.07it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-w5l_9eqr.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-w5l_9eqr.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x8be408e7

INFO:gurobipy:Model fingerprint: 0x8be408e7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3288 columns

INFO:gurobipy:Presolve removed 23608 rows and 3288 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8760 columns, 20344 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8760 columns, 20344 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.01s

INFO:gurobipy:Ordering time: 0.01s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.04275179e+13 -1.03681726e+13  5.83e+08 7.99e+01  1.95e+11     0s

INFO:gurobipy:   0   2.04275179e+13 -1.03681726e+13  5.83e+08 7.99e+01  1.95e+11     0s

   1   1.88953456e+12 -7.87360406e+12  5.21e+07 1.21e+04  1.79e+10     0s

INFO:gurobipy:   1   1.88953456e+12 -7.87360406e+12  5.21e+07 1.21e+04  1.79e+10     0s

   2   2.57228672e+11 -2.57592258e+12  6.82e+06 5.46e-11  2.40e+09     0s

INFO:gurobipy:   2   2.57228672e+11 -2.57592258e+12  6.82e+06 5.46e-11  2.40e+09     0s

   3   2.95389108e+10 -7.97027897e+11  5.77e+05 5.96e-11  2.33e+08     0s

INFO:gurobipy:   3   2.95389108e+10 -7.97027897e+11  5.77e+05 5.96e-11  2.33e+08     0s

INFO:gurobipy:

Barrier performed 3 iterations in 0.08 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 3 iterations in 0.08 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1772    1.4758780e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1772    1.4758780e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1772 iterations and 0.10 seconds (0.06 work units)

INFO:gurobipy:Solved in 1772 iterations and 0.10 seconds (0.06 work units)

Optimal objective  1.475877955e+09

INFO:gurobipy:Optimal objective  1.475877955e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.48e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-10 00:00:00:2019-10-15 21:00:00] (48/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.03it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.85it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-kitundp5.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-kitundp5.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xa1a1d80b

INFO:gurobipy:Model fingerprint: 0xa1a1d80b

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3479 columns

INFO:gurobipy:Presolve removed 23608 rows and 3479 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1209 rows, 8569 columns, 19987 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8569 columns, 19987 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.00529114e+13 -1.03290815e+13  5.86e+08 1.60e+03  1.95e+11     0s

INFO:gurobipy:   0   2.00529114e+13 -1.03290815e+13  5.86e+08 1.60e+03  1.95e+11     0s

   1   1.97748503e+12 -7.86608540e+12  5.68e+07 1.23e+04  1.94e+10     0s

INFO:gurobipy:   1   1.97748503e+12 -7.86608540e+12  5.68e+07 1.23e+04  1.94e+10     0s

   2   2.73341897e+11 -2.64677219e+12  7.56e+06 5.86e-11  2.67e+09     0s

INFO:gurobipy:   2   2.73341897e+11 -2.64677219e+12  7.56e+06 5.86e-11  2.67e+09     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.10 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.10 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1748    1.0677365e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1748    1.0677365e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1748 iterations and 0.12 seconds (0.06 work units)

INFO:gurobipy:Solved in 1748 iterations and 0.12 seconds (0.06 work units)

Optimal objective  1.067736451e+09

INFO:gurobipy:Optimal objective  1.067736451e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.07e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-16 00:00:00:2019-10-21 21:00:00] (49/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 93.00it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 249.89it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7m2vqmpc.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7m2vqmpc.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x21188161

INFO:gurobipy:Model fingerprint: 0x21188161

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3360 columns

INFO:gurobipy:Presolve removed 23608 rows and 3360 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8688 columns, 20228 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8688 columns, 20228 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.01885233e+13 -1.03446665e+13  5.92e+08 1.47e+03  1.97e+11     0s

INFO:gurobipy:   0   2.01885233e+13 -1.03446665e+13  5.92e+08 1.47e+03  1.97e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1542    1.4455358e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1542    1.4455358e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1542 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1542 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.445535811e+09

INFO:gurobipy:Optimal objective  1.445535811e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.45e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-22 00:00:00:2019-10-27 21:00:00] (50/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.91it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 251.70it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-883jdrzu.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-883jdrzu.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x68734a09

INFO:gurobipy:Model fingerprint: 0x68734a09

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3354 columns

INFO:gurobipy:Presolve removed 23608 rows and 3354 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8694 columns, 20244 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8694 columns, 20244 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.04109050e+13 -1.03563618e+13  5.98e+08 1.51e+03  1.99e+11     0s

INFO:gurobipy:   0   2.04109050e+13 -1.03563618e+13  5.98e+08 1.51e+03  1.99e+11     0s

   1   2.28481696e+12 -7.76728767e+12  6.36e+07 1.13e+04  2.17e+10     0s

INFO:gurobipy:   1   2.28481696e+12 -7.76728767e+12  6.36e+07 1.13e+04  2.17e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1549    1.3673420e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1549    1.3673420e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1549 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1549 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.367341953e+09

INFO:gurobipy:Optimal objective  1.367341953e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.37e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-28 00:00:00:2019-11-02 21:00:00] (51/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.77it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 255.19it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mj9d7p95.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mj9d7p95.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xffbc2649

INFO:gurobipy:Model fingerprint: 0xffbc2649

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3305 columns

INFO:gurobipy:Presolve removed 23608 rows and 3305 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1209 rows, 8743 columns, 20327 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8743 columns, 20327 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.14155542e+13 -1.03598066e+13  6.04e+08 7.97e+01  2.02e+11     0s

INFO:gurobipy:   0   2.14155542e+13 -1.03598066e+13  6.04e+08 7.97e+01  2.02e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.22 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.22 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1514    2.2850811e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1514    2.2850811e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1514 iterations and 0.24 seconds (0.05 work units)

INFO:gurobipy:Solved in 1514 iterations and 0.24 seconds (0.05 work units)

Optimal objective  2.285081098e+09

INFO:gurobipy:Optimal objective  2.285081098e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.29e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-03 00:00:00:2019-11-08 21:00:00] (52/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.01it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.31it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-eh3kxo_m.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-eh3kxo_m.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xce37c7e7

INFO:gurobipy:Model fingerprint: 0xce37c7e7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23620 rows and 3345 columns

INFO:gurobipy:Presolve removed 23620 rows and 3345 columns

Presolve time: 0.14s

INFO:gurobipy:Presolve time: 0.14s

Presolved: 1197 rows, 8703 columns, 20275 nonzeros

INFO:gurobipy:Presolved: 1197 rows, 8703 columns, 20275 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.928e+03

INFO:gurobipy: AA' NZ     : 3.928e+03

 Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 3.024e+04 (roughly 4 MB of memory)

 Factor Ops : 1.217e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.217e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.70189871e+13 -8.54624033e+12  7.62e+08 8.06e+01  2.55e+11     0s

INFO:gurobipy:   0   2.70189871e+13 -8.54624033e+12  7.62e+08 8.06e+01  2.55e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.19 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.19 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1410    2.5558320e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1410    2.5558320e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1410 iterations and 0.22 seconds (0.05 work units)

INFO:gurobipy:Solved in 1410 iterations and 0.22 seconds (0.05 work units)

Optimal objective  2.555832002e+09

INFO:gurobipy:Optimal objective  2.555832002e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.56e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-09 00:00:00:2019-11-14 21:00:00] (53/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 81.84it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 221.65it/s]
INFO:linopy.io: Writing time: 0.27s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-jg0ggy28.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-jg0ggy28.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x6500947d

INFO:gurobipy:Model fingerprint: 0x6500947d

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23627 rows and 3337 columns

INFO:gurobipy:Presolve removed 23627 rows and 3337 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1190 rows, 8711 columns, 20276 nonzeros

INFO:gurobipy:Presolved: 1190 rows, 8711 columns, 20276 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.01s

INFO:gurobipy:Ordering time: 0.01s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.915e+03

INFO:gurobipy: AA' NZ     : 3.915e+03

 Factor NZ  : 2.671e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.671e+04 (roughly 4 MB of memory)

 Factor Ops : 8.711e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 8.711e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.25474829e+13 -9.84989299e+12  6.31e+08 7.85e+01  2.11e+11     0s

INFO:gurobipy:   0   2.25474829e+13 -9.84989299e+12  6.31e+08 7.85e+01  2.11e+11     0s

   1   2.17460737e+12 -7.30946905e+12  5.95e+07 1.20e+04  2.03e+10     0s

INFO:gurobipy:   1   2.17460737e+12 -7.30946905e+12  5.95e+07 1.20e+04  2.03e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1569    2.3480033e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1569    2.3480033e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1569 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1569 iterations and 0.12 seconds (0.05 work units)

Optimal objective  2.348003312e+09

INFO:gurobipy:Optimal objective  2.348003312e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.35e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-15 00:00:00:2019-11-20 21:00:00] (54/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 84.31it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 226.85it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-p6mdz_as.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-p6mdz_as.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0b4e04e4

INFO:gurobipy:Model fingerprint: 0x0b4e04e4

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23627 rows and 3360 columns

INFO:gurobipy:Presolve removed 23627 rows and 3360 columns

Presolve time: 0.07s

INFO:gurobipy:Presolve time: 0.07s

Presolved: 1190 rows, 8688 columns, 20253 nonzeros

INFO:gurobipy:Presolved: 1190 rows, 8688 columns, 20253 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.915e+03

INFO:gurobipy: AA' NZ     : 3.915e+03

 Factor NZ  : 2.671e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.671e+04 (roughly 4 MB of memory)

 Factor Ops : 8.711e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 8.711e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.30590497e+13 -9.84004024e+12  6.45e+08 8.22e+01  2.16e+11     0s

INFO:gurobipy:   0   2.30590497e+13 -9.84004024e+12  6.45e+08 8.22e+01  2.16e+11     0s

   1   2.25805710e+12 -7.30591067e+12  6.18e+07 1.20e+04  2.11e+10     0s

INFO:gurobipy:   1   2.25805710e+12 -7.30591067e+12  6.18e+07 1.20e+04  2.11e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1567    2.5525524e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1567    2.5525524e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1567 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1567 iterations and 0.12 seconds (0.05 work units)

Optimal objective  2.552552399e+09

INFO:gurobipy:Optimal objective  2.552552399e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.55e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-21 00:00:00:2019-11-26 21:00:00] (55/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.33it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 242.85it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-suxrx_ge.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-suxrx_ge.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x4d9fba18

INFO:gurobipy:Model fingerprint: 0x4d9fba18

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23624 rows and 3344 columns

INFO:gurobipy:Presolve removed 23624 rows and 3344 columns

Presolve time: 0.07s

INFO:gurobipy:Presolve time: 0.07s

Presolved: 1193 rows, 8704 columns, 20272 nonzeros

INFO:gurobipy:Presolved: 1193 rows, 8704 columns, 20272 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.920e+03

INFO:gurobipy: AA' NZ     : 3.920e+03

 Factor NZ  : 2.724e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.724e+04 (roughly 4 MB of memory)

 Factor Ops : 9.167e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.167e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.89519073e+13 -7.96662826e+12  8.10e+08 9.47e+01  2.71e+11     0s

INFO:gurobipy:   0   2.89519073e+13 -7.96662826e+12  8.10e+08 9.47e+01  2.71e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1464    2.6627746e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1464    2.6627746e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1464 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1464 iterations and 0.13 seconds (0.05 work units)

Optimal objective  2.662774648e+09

INFO:gurobipy:Optimal objective  2.662774648e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.66e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-27 00:00:00:2019-12-02 21:00:00] (56/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 89.95it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.59it/s]
INFO:linopy.io: Writing time: 0.35s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3htpu6_w.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3htpu6_w.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xb2d09fe7

INFO:gurobipy:Model fingerprint: 0xb2d09fe7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3342 columns

INFO:gurobipy:Presolve removed 23614 rows and 3342 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8706 columns, 20284 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8706 columns, 20284 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.940e+03

INFO:gurobipy: AA' NZ     : 3.940e+03

 Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

 Factor Ops : 9.535e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.535e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.40088327e+13 -9.12160960e+12  6.74e+08 9.91e+01  2.26e+11     0s

INFO:gurobipy:   0   2.40088327e+13 -9.12160960e+12  6.74e+08 9.91e+01  2.26e+11     0s

   1   2.57718926e+12 -6.61350142e+12  7.09e+07 1.17e+04  2.41e+10     0s

INFO:gurobipy:   1   2.57718926e+12 -6.61350142e+12  7.09e+07 1.17e+04  2.41e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1620    2.1681174e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1620    2.1681174e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1620 iterations and 0.15 seconds (0.05 work units)

INFO:gurobipy:Solved in 1620 iterations and 0.15 seconds (0.05 work units)

Optimal objective  2.168117367e+09

INFO:gurobipy:Optimal objective  2.168117367e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.17e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-03 00:00:00:2019-12-08 21:00:00] (57/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 74.85it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 231.89it/s]
INFO:linopy.io: Writing time: 0.29s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hudkyj8o.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hudkyj8o.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xee879a97

INFO:gurobipy:Model fingerprint: 0xee879a97

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3334 columns

INFO:gurobipy:Presolve removed 23614 rows and 3334 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8714 columns, 20292 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8714 columns, 20292 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.940e+03

INFO:gurobipy: AA' NZ     : 3.940e+03

 Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

 Factor Ops : 9.535e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.535e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.43956869e+13 -9.08370353e+12  6.88e+08 8.54e+01  2.29e+11     0s

INFO:gurobipy:   0   2.43956869e+13 -9.08370353e+12  6.88e+08 8.54e+01  2.29e+11     0s

   1   2.77942139e+12 -6.51091317e+12  7.69e+07 1.12e+04  2.60e+10     0s

INFO:gurobipy:   1   2.77942139e+12 -6.51091317e+12  7.69e+07 1.12e+04  2.60e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1785    1.8160192e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1785    1.8160192e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1785 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1785 iterations and 0.13 seconds (0.05 work units)

Optimal objective  1.816019157e+09

INFO:gurobipy:Optimal objective  1.816019157e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.82e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-09 00:00:00:2019-12-14 21:00:00] (58/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 77.22it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.19it/s]
INFO:linopy.io: Writing time: 0.28s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8ec2sskw.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8ec2sskw.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xca26569c

INFO:gurobipy:Model fingerprint: 0xca26569c

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3328 columns

INFO:gurobipy:Presolve removed 23614 rows and 3328 columns

Presolve time: 0.08s

INFO:gurobipy:Presolve time: 0.08s

Presolved: 1203 rows, 8720 columns, 20298 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8720 columns, 20298 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.940e+03

INFO:gurobipy: AA' NZ     : 3.940e+03

 Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

 Factor Ops : 9.535e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.535e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.48893173e+13 -9.13832334e+12  6.97e+08 7.88e+01  2.33e+11     0s

INFO:gurobipy:   0   2.48893173e+13 -9.13832334e+12  6.97e+08 7.88e+01  2.33e+11     0s

   1   2.75212136e+12 -6.57768301e+12  7.56e+07 1.13e+04  2.57e+10     0s

INFO:gurobipy:   1   2.75212136e+12 -6.57768301e+12  7.56e+07 1.13e+04  2.57e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.12 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.12 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1645    1.9109892e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1645    1.9109892e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1645 iterations and 0.15 seconds (0.05 work units)

INFO:gurobipy:Solved in 1645 iterations and 0.15 seconds (0.05 work units)

Optimal objective  1.910989179e+09

INFO:gurobipy:Optimal objective  1.910989179e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.91e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-15 00:00:00:2019-12-20 21:00:00] (59/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 89.12it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 256.34it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-wabu25im.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-wabu25im.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x327d29c4

INFO:gurobipy:Model fingerprint: 0x327d29c4

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3330 columns

INFO:gurobipy:Presolve removed 23614 rows and 3330 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8718 columns, 20296 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8718 columns, 20296 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.940e+03

INFO:gurobipy: AA' NZ     : 3.940e+03

 Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

 Factor Ops : 9.535e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.535e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.52344032e+13 -9.13270934e+12  7.08e+08 8.28e+01  2.37e+11     0s

INFO:gurobipy:   0   2.52344032e+13 -9.13270934e+12  7.08e+08 8.28e+01  2.37e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.20 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.20 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1649    1.5094117e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1649    1.5094117e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1649 iterations and 0.22 seconds (0.05 work units)

INFO:gurobipy:Solved in 1649 iterations and 0.22 seconds (0.05 work units)

Optimal objective  1.509411700e+09

INFO:gurobipy:Optimal objective  1.509411700e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.51e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-21 00:00:00:2019-12-26 21:00:00] (60/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 90.35it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.92it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_k_6de6f.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-_k_6de6f.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xceeb3451

INFO:gurobipy:Model fingerprint: 0xceeb3451

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3328 columns

INFO:gurobipy:Presolve removed 23614 rows and 3328 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8720 columns, 20298 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8720 columns, 20298 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.940e+03

INFO:gurobipy: AA' NZ     : 3.940e+03

 Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.778e+04 (roughly 4 MB of memory)

 Factor Ops : 9.535e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.535e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.55760316e+13 -9.11583051e+12  7.16e+08 8.57e+01  2.40e+11     0s

INFO:gurobipy:   0   2.55760316e+13 -9.11583051e+12  7.16e+08 8.57e+01  2.40e+11     0s

   1   2.67110292e+12 -6.56008568e+12  7.33e+07 1.16e+04  2.49e+10     0s

INFO:gurobipy:   1   2.67110292e+12 -6.56008568e+12  7.33e+07 1.16e+04  2.49e+10     0s

   2   5.26329222e+11 -2.78045634e+12  1.42e+07 5.81e+01  4.92e+09     0s

INFO:gurobipy:   2   5.26329222e+11 -2.78045634e+12  1.42e+07 5.81e+01  4.92e+09     0s

   3   3.93501573e+10 -1.11997095e+12  8.05e+05 5.86e-11  3.34e+08     0s

INFO:gurobipy:   3   3.93501573e+10 -1.11997095e+12  8.05e+05 5.86e-11  3.34e+08     0s

INFO:gurobipy:

Barrier performed 3 iterations in 0.11 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 3 iterations in 0.11 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1854    2.0295730e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1854    2.0295730e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1854 iterations and 0.13 seconds (0.06 work units)

INFO:gurobipy:Solved in 1854 iterations and 0.13 seconds (0.06 work units)

Optimal objective  2.029573008e+09

INFO:gurobipy:Optimal objective  2.029573008e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.03e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-27 00:00:00:2019-12-31 21:00:00] (61/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 101.85it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.66it/s]
INFO:linopy.io: Writing time: 0.22s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-r69dliq8.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-r69dliq8.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 20681 rows, 10040 columns, 40796 nonzeros

INFO:gurobipy:obj: 20681 rows, 10040 columns, 40796 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 20681 rows, 10040 columns and 40796 nonzeros

INFO:gurobipy:Optimize a model with 20681 rows, 10040 columns and 40796 nonzeros

Model fingerprint: 0x7396735e

INFO:gurobipy:Model fingerprint: 0x7396735e

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 19678 rows and 2783 columns

INFO:gurobipy:Presolve removed 19678 rows and 2783 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1003 rows, 7257 columns, 16907 nonzeros

INFO:gurobipy:Presolved: 1003 rows, 7257 columns, 16907 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.284e+03

INFO:gurobipy: AA' NZ     : 3.284e+03

 Factor NZ  : 2.279e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.279e+04 (roughly 4 MB of memory)

 Factor Ops : 7.439e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 7.439e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.84763198e+13 -6.55050350e+12  9.72e+08 9.22e+01  3.22e+11     0s

INFO:gurobipy:   0   2.84763198e+13 -6.55050350e+12  9.72e+08 9.22e+01  3.22e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1263    2.1039663e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1263    2.1039663e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1263 iterations and 0.12 seconds (0.04 work units)

INFO:gurobipy:Solved in 1263 iterations and 0.12 seconds (0.04 work units)

Optimal objective  2.103966329e+09

INFO:gurobipy:Optimal objective  2.103966329e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 10040 primals, 20681 duals
Objective: 2.10e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.

historic wind data ohne biomass und rolling horizon

In [28]:
n_rh_without_biomass = n_lt.copy()
add_carbon_price(n_rh_without_biomass, co2_prices["2035"], specific_emissions)
build_st_network(n_rh_without_biomass)

n_rh_without_biomass.optimize.optimize_with_rolling_horizon(
    horizon = horizon,
    overlap = 0,
    solver_name='gurobi'
)

WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-01 00:00:00:2019-01-06 21:00:00] (1/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.43it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 232.07it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4nevmmjl.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4nevmmjl.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xe400fa48

INFO:gurobipy:Model fingerprint: 0xe400fa48

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3338 columns

INFO:gurobipy:Presolve removed 23612 rows and 3338 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1205 rows, 8710 columns, 17257 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8710 columns, 17257 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.315e+03

INFO:gurobipy: AA' NZ     : 3.315e+03

 Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

 Factor Ops : 1.100e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.100e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.08506170e+11 -2.92200437e+12  6.49e+05 6.65e+01  1.50e+09     0s

INFO:gurobipy:   0   1.08506170e+11 -2.92200437e+12  6.49e+05 6.65e+01  1.50e+09     0s

   1   1.43794983e+10 -5.74091099e+11  3.30e+04 5.44e-11  9.70e+07     0s

INFO:gurobipy:   1   1.43794983e+10 -5.74091099e+11  3.30e+04 5.44e-11  9.70e+07     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1603    1.4796964e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1603    1.4796964e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1603 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1603 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.479696417e+09

INFO:gurobipy:Optimal objective  1.479696417e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.48e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-07 00:00:00:2019-01-12 21:00:00] (2/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 82.83it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 231.39it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nzyzv42d.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nzyzv42d.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x805ac64d

INFO:gurobipy:Model fingerprint: 0x805ac64d

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3337 columns

INFO:gurobipy:Presolve removed 23613 rows and 3337 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1204 rows, 8711 columns, 17257 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8711 columns, 17257 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.22749729e+11 -2.98167878e+12  7.45e+05 6.65e+01  1.70e+09     0s

INFO:gurobipy:   0   1.22749729e+11 -2.98167878e+12  7.45e+05 6.65e+01  1.70e+09     0s

   1   1.47165559e+10 -6.15057953e+11  3.41e+04 4.72e-11  1.02e+08     0s

INFO:gurobipy:   1   1.47165559e+10 -6.15057953e+11  3.41e+04 4.72e-11  1.02e+08     0s

   2   6.25892896e+09 -1.46138021e+11  2.86e+03 4.44e-10  1.31e+07     0s

INFO:gurobipy:   2   6.25892896e+09 -1.46138021e+11  2.86e+03 4.44e-10  1.31e+07     0s

   3   3.56916498e+09 -2.85193702e+10  4.69e+02 8.71e-10  2.33e+06     0s

INFO:gurobipy:   3   3.56916498e+09 -2.85193702e+10  4.69e+02 8.71e-10  2.33e+06     0s

INFO:gurobipy:

Barrier performed 3 iterations in 0.07 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 3 iterations in 0.07 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1769    1.5357571e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1769    1.5357571e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1769 iterations and 0.09 seconds (0.06 work units)

INFO:gurobipy:Solved in 1769 iterations and 0.09 seconds (0.06 work units)

Optimal objective  1.535757092e+09

INFO:gurobipy:Optimal objective  1.535757092e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.54e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-13 00:00:00:2019-01-18 21:00:00] (3/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.85it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 241.52it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fk3i_edb.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fk3i_edb.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xb918aed7

INFO:gurobipy:Model fingerprint: 0xb918aed7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3340 columns

INFO:gurobipy:Presolve removed 23614 rows and 3340 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8708 columns, 17253 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8708 columns, 17253 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.313e+03

INFO:gurobipy: AA' NZ     : 3.313e+03

 Factor NZ  : 2.756e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.756e+04 (roughly 4 MB of memory)

 Factor Ops : 9.118e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.118e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.28146367e+11 -3.05929169e+12  7.84e+05 7.02e+01  1.78e+09     0s

INFO:gurobipy:   0   1.28146367e+11 -3.05929169e+12  7.84e+05 7.02e+01  1.78e+09     0s

   1   1.46186627e+10 -6.34832095e+11  3.45e+04 6.87e-11  1.04e+08     0s

INFO:gurobipy:   1   1.46186627e+10 -6.34832095e+11  3.45e+04 6.87e-11  1.04e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1700    1.2499722e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1700    1.2499722e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1700 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1700 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.249972174e+09

INFO:gurobipy:Optimal objective  1.249972174e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.25e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-19 00:00:00:2019-01-24 21:00:00] (4/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.05it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 236.57it/s]
INFO:linopy.io: Writing time: 0.27s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-bqx7nwby.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-bqx7nwby.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc24270a2

INFO:gurobipy:Model fingerprint: 0xc24270a2

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23616 rows and 3447 columns

INFO:gurobipy:Presolve removed 23616 rows and 3447 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1201 rows, 8601 columns, 17124 nonzeros

INFO:gurobipy:Presolved: 1201 rows, 8601 columns, 17124 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.311e+03

INFO:gurobipy: AA' NZ     : 3.311e+03

 Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

 Factor Ops : 1.072e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.072e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.30583822e+11 -3.16418907e+12  1.52e+06 1.09e+02  3.28e+09     0s

INFO:gurobipy:   0   2.30583822e+11 -3.16418907e+12  1.52e+06 1.09e+02  3.28e+09     0s

   1   2.11550524e+10 -8.57639531e+11  6.75e+04 4.58e-11  1.84e+08     0s

INFO:gurobipy:   1   2.11550524e+10 -8.57639531e+11  6.75e+04 4.58e-11  1.84e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1595    4.3333144e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1595    4.3333144e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1595 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1595 iterations and 0.09 seconds (0.05 work units)

Optimal objective  4.333314382e+09

INFO:gurobipy:Optimal objective  4.333314382e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 4.33e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-25 00:00:00:2019-01-30 21:00:00] (5/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 93.81it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 240.01it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6m2uonnh.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6m2uonnh.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0ebf70ac

INFO:gurobipy:Model fingerprint: 0x0ebf70ac

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3362 columns

INFO:gurobipy:Presolve removed 23611 rows and 3362 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8686 columns, 17232 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8686 columns, 17232 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.22882991e+11 -2.77087763e+12  7.50e+05 9.76e+01  1.69e+09     0s

INFO:gurobipy:   0   1.22882991e+11 -2.77087763e+12  7.50e+05 9.76e+01  1.69e+09     0s

   1   1.49199140e+10 -6.09335857e+11  3.40e+04 5.35e-11  1.02e+08     0s

INFO:gurobipy:   1   1.49199140e+10 -6.09335857e+11  3.40e+04 5.35e-11  1.02e+08     0s

   2   7.49026122e+09 -1.71196597e+11  3.50e+03 2.81e-10  1.58e+07     0s

INFO:gurobipy:   2   7.49026122e+09 -1.71196597e+11  3.50e+03 2.81e-10  1.58e+07     0s

   3   4.86615823e+09 -4.43917298e+10  9.18e+02 2.06e-10  3.91e+06     0s

INFO:gurobipy:   3   4.86615823e+09 -4.43917298e+10  9.18e+02 2.06e-10  3.91e+06     0s

INFO:gurobipy:

Barrier performed 3 iterations in 0.07 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 3 iterations in 0.07 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1904    1.9348902e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1904    1.9348902e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1904 iterations and 0.09 seconds (0.06 work units)

INFO:gurobipy:Solved in 1904 iterations and 0.09 seconds (0.06 work units)

Optimal objective  1.934890172e+09

INFO:gurobipy:Optimal objective  1.934890172e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.93e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-01-31 00:00:00:2019-02-05 21:00:00] (6/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 93.66it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 257.94it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x9_jt33h.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x9_jt33h.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xba42afb2

INFO:gurobipy:Model fingerprint: 0xba42afb2

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3320 columns

INFO:gurobipy:Presolve removed 23611 rows and 3320 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1206 rows, 8728 columns, 17276 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8728 columns, 17276 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.29798782e+11 -2.76969461e+12  7.95e+05 6.81e+01  1.79e+09     0s

INFO:gurobipy:   0   1.29798782e+11 -2.76969461e+12  7.95e+05 6.81e+01  1.79e+09     0s

   1   1.50982163e+10 -6.22925233e+11  3.44e+04 4.62e-11  1.03e+08     0s

INFO:gurobipy:   1   1.50982163e+10 -6.22925233e+11  3.44e+04 4.62e-11  1.03e+08     0s

   2   7.74691834e+09 -1.29806014e+11  3.22e+03 1.17e-09  1.29e+07     0s

INFO:gurobipy:   2   7.74691834e+09 -1.29806014e+11  3.22e+03 1.17e-09  1.29e+07     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1743    2.1869124e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1743    2.1869124e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1743 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1743 iterations and 0.12 seconds (0.05 work units)

Optimal objective  2.186912448e+09

INFO:gurobipy:Optimal objective  2.186912448e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.19e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-06 00:00:00:2019-02-11 21:00:00] (7/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.09it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.28it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-715bhgm1.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-715bhgm1.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x35a15051

INFO:gurobipy:Model fingerprint: 0x35a15051

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3290 columns

INFO:gurobipy:Presolve removed 23611 rows and 3290 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8758 columns, 17306 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.46036013e+11 -2.78906482e+12  9.05e+05 6.49e+01  2.01e+09     0s

INFO:gurobipy:   0   1.46036013e+11 -2.78906482e+12  9.05e+05 6.49e+01  2.01e+09     0s

   1   1.53716257e+10 -6.81664332e+11  3.92e+04 4.71e-11  1.16e+08     0s

INFO:gurobipy:   1   1.53716257e+10 -6.81664332e+11  3.92e+04 4.71e-11  1.16e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1718    1.1690379e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1718    1.1690379e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1718 iterations and 0.08 seconds (0.05 work units)

INFO:gurobipy:Solved in 1718 iterations and 0.08 seconds (0.05 work units)

Optimal objective  1.169037938e+09

INFO:gurobipy:Optimal objective  1.169037938e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.17e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-12 00:00:00:2019-02-17 21:00:00] (8/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.94it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 235.86it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8c8aju4o.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8c8aju4o.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x03566331

INFO:gurobipy:Model fingerprint: 0x03566331

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3276 columns

INFO:gurobipy:Presolve removed 23612 rows and 3276 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1205 rows, 8772 columns, 17319 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8772 columns, 17319 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.315e+03

INFO:gurobipy: AA' NZ     : 3.315e+03

 Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.890e+04 (roughly 4 MB of memory)

 Factor Ops : 1.100e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.100e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.68478617e+11 -2.91855562e+12  1.06e+06 6.33e+01  2.33e+09     0s

INFO:gurobipy:   0   1.68478617e+11 -2.91855562e+12  1.06e+06 6.33e+01  2.33e+09     0s

   1   1.68864012e+10 -7.32526465e+11  4.64e+04 5.64e-11  1.33e+08     0s

INFO:gurobipy:   1   1.68864012e+10 -7.32526465e+11  4.64e+04 5.64e-11  1.33e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1632    1.3934519e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1632    1.3934519e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1632 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1632 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.393451948e+09

INFO:gurobipy:Optimal objective  1.393451948e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.39e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-18 00:00:00:2019-02-23 21:00:00] (9/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.32it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.80it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qx30ifgd.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qx30ifgd.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x21f0f236

INFO:gurobipy:Model fingerprint: 0x21f0f236

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3277 columns

INFO:gurobipy:Presolve removed 23613 rows and 3277 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1204 rows, 8771 columns, 17317 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8771 columns, 17317 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.67194579e+11 -2.95664288e+12  1.05e+06 6.37e+01  2.31e+09     0s

INFO:gurobipy:   0   1.67194579e+11 -2.95664288e+12  1.05e+06 6.37e+01  2.31e+09     0s

   1   1.68317147e+10 -7.26432159e+11  4.60e+04 5.60e-11  1.32e+08     0s

INFO:gurobipy:   1   1.68317147e+10 -7.26432159e+11  4.60e+04 5.60e-11  1.32e+08     0s

   2   6.14191620e+09 -1.58758314e+11  2.47e+03 1.20e-09  1.33e+07     0s

INFO:gurobipy:   2   6.14191620e+09 -1.58758314e+11  2.47e+03 1.20e-09  1.33e+07     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1699    1.4622147e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1699    1.4622147e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1699 iterations and 0.19 seconds (0.05 work units)

INFO:gurobipy:Solved in 1699 iterations and 0.19 seconds (0.05 work units)

Optimal objective  1.462214717e+09

INFO:gurobipy:Optimal objective  1.462214717e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.46e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-02-24 00:00:00:2019-03-01 21:00:00] (10/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.67it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 246.40it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nl88a930.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nl88a930.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xf535f86a

INFO:gurobipy:Model fingerprint: 0xf535f86a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3292 columns

INFO:gurobipy:Presolve removed 23613 rows and 3292 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1204 rows, 8756 columns, 17302 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8756 columns, 17302 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.75894203e+11 -2.97744349e+12  1.11e+06 7.51e+01  2.44e+09     0s

INFO:gurobipy:   0   1.75894203e+11 -2.97744349e+12  1.11e+06 7.51e+01  2.44e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.13 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.13 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1673    1.6432621e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1673    1.6432621e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1673 iterations and 0.16 seconds (0.05 work units)

INFO:gurobipy:Solved in 1673 iterations and 0.16 seconds (0.05 work units)

Optimal objective  1.643262148e+09

INFO:gurobipy:Optimal objective  1.643262148e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.64e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-02 00:00:00:2019-03-07 21:00:00] (11/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.65it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 241.09it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-j_h6hgs_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-j_h6hgs_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x0dcb8f8c

INFO:gurobipy:Model fingerprint: 0x0dcb8f8c

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23613 rows and 3283 columns

INFO:gurobipy:Presolve removed 23613 rows and 3283 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1204 rows, 8765 columns, 17311 nonzeros

INFO:gurobipy:Presolved: 1204 rows, 8765 columns, 17311 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.314e+03

INFO:gurobipy: AA' NZ     : 3.314e+03

 Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.902e+04 (roughly 4 MB of memory)

 Factor Ops : 1.117e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.117e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.87160573e+11 -3.02372929e+12  1.19e+06 6.37e+01  2.61e+09     0s

INFO:gurobipy:   0   1.87160573e+11 -3.02372929e+12  1.19e+06 6.37e+01  2.61e+09     0s

   1   1.75165030e+10 -7.87279024e+11  5.23e+04 5.49e-11  1.48e+08     0s

INFO:gurobipy:   1   1.75165030e+10 -7.87279024e+11  5.23e+04 5.49e-11  1.48e+08     0s

   2   5.02352790e+09 -1.74408569e+11  2.62e+03 1.36e-09  1.44e+07     0s

INFO:gurobipy:   2   5.02352790e+09 -1.74408569e+11  2.62e+03 1.36e-09  1.44e+07     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1772    1.0272489e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1772    1.0272489e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1772 iterations and 0.12 seconds (0.06 work units)

INFO:gurobipy:Solved in 1772 iterations and 0.12 seconds (0.06 work units)

Optimal objective  1.027248900e+09

INFO:gurobipy:Optimal objective  1.027248900e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.03e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-08 00:00:00:2019-03-13 21:00:00] (12/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 89.75it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 225.08it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-e84459mj.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-e84459mj.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x2328366b

INFO:gurobipy:Model fingerprint: 0x2328366b

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 4e+02]

INFO:gurobipy:  Bounds range     [4e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23616 rows and 3280 columns

INFO:gurobipy:Presolve removed 23616 rows and 3280 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1201 rows, 8768 columns, 17311 nonzeros

INFO:gurobipy:Presolved: 1201 rows, 8768 columns, 17311 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.311e+03

INFO:gurobipy: AA' NZ     : 3.311e+03

 Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.867e+04 (roughly 4 MB of memory)

 Factor Ops : 1.072e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.072e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.94863524e+11 -3.16148640e+12  1.24e+06 6.37e+01  2.71e+09     0s

INFO:gurobipy:   0   1.94863524e+11 -3.16148640e+12  1.24e+06 6.37e+01  2.71e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1683    1.0264294e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1683    1.0264294e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1683 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1683 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.026429416e+09

INFO:gurobipy:Optimal objective  1.026429416e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.03e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-14 00:00:00:2019-03-19 21:00:00] (13/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 88.33it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.34it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hlr2lmmn.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-hlr2lmmn.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xab173451

INFO:gurobipy:Model fingerprint: 0xab173451

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 6e+02]

INFO:gurobipy:  Bounds range     [4e+02, 6e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23618 rows and 3283 columns

INFO:gurobipy:Presolve removed 23618 rows and 3283 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1199 rows, 8765 columns, 17306 nonzeros

INFO:gurobipy:Presolved: 1199 rows, 8765 columns, 17306 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.309e+03

INFO:gurobipy: AA' NZ     : 3.309e+03

 Factor NZ  : 2.752e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.752e+04 (roughly 4 MB of memory)

 Factor Ops : 9.315e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.315e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.02932024e+11 -3.30764649e+12  1.29e+06 6.38e+01  2.84e+09     0s

INFO:gurobipy:   0   2.02932024e+11 -3.30764649e+12  1.29e+06 6.38e+01  2.84e+09     0s

   1   1.84587890e+10 -8.08287731e+11  5.70e+04 5.74e-11  1.59e+08     0s

INFO:gurobipy:   1   1.84587890e+10 -8.08287731e+11  5.70e+04 5.74e-11  1.59e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1726    1.0447989e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1726    1.0447989e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1726 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1726 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.044798931e+09

INFO:gurobipy:Optimal objective  1.044798931e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.04e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-20 00:00:00:2019-03-25 21:00:00] (14/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.54it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 249.16it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yv3he2v7.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-yv3he2v7.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xabb65dae

INFO:gurobipy:Model fingerprint: 0xabb65dae

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 7e+02]

INFO:gurobipy:  Bounds range     [5e+02, 7e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23621 rows and 3303 columns

INFO:gurobipy:Presolve removed 23621 rows and 3303 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1196 rows, 8745 columns, 17283 nonzeros

INFO:gurobipy:Presolved: 1196 rows, 8745 columns, 17283 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.306e+03

INFO:gurobipy: AA' NZ     : 3.306e+03

 Factor NZ  : 2.786e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.786e+04 (roughly 4 MB of memory)

 Factor Ops : 9.611e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.611e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.21276103e+11 -3.39686717e+12  1.48e+06 7.95e+01  3.10e+09     0s

INFO:gurobipy:   0   2.21276103e+11 -3.39686717e+12  1.48e+06 7.95e+01  3.10e+09     0s

   1   1.98241758e+10 -8.24454305e+11  6.59e+04 4.68e-11  1.73e+08     0s

INFO:gurobipy:   1   1.98241758e+10 -8.24454305e+11  6.59e+04 4.68e-11  1.73e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.18 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.18 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1646    1.2432651e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1646    1.2432651e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1646 iterations and 0.23 seconds (0.05 work units)

INFO:gurobipy:Solved in 1646 iterations and 0.23 seconds (0.05 work units)

Optimal objective  1.243265057e+09

INFO:gurobipy:Optimal objective  1.243265057e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.24e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-03-26 00:00:00:2019-03-31 21:00:00] (15/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 54.85it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.67it/s]
INFO:linopy.io: Writing time: 0.37s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rly50rp4.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rly50rp4.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x858fda9c

INFO:gurobipy:Model fingerprint: 0x858fda9c

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 5e+02]

INFO:gurobipy:  Bounds range     [5e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23622 rows and 3293 columns

INFO:gurobipy:Presolve removed 23622 rows and 3293 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1195 rows, 8755 columns, 17292 nonzeros

INFO:gurobipy:Presolved: 1195 rows, 8755 columns, 17292 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.305e+03

INFO:gurobipy: AA' NZ     : 3.305e+03

 Factor NZ  : 2.787e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.787e+04 (roughly 4 MB of memory)

 Factor Ops : 9.333e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.333e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.39660486e+11 -3.44255763e+12  1.75e+06 6.39e+01  3.36e+09     0s

INFO:gurobipy:   0   2.39660486e+11 -3.44255763e+12  1.75e+06 6.39e+01  3.36e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1539    1.3251074e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1539    1.3251074e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1539 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1539 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.325107445e+09

INFO:gurobipy:Optimal objective  1.325107445e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.33e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-01 00:00:00:2019-04-06 21:00:00] (16/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.92it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.42it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rzuulbzm.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-rzuulbzm.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc5c44c72

INFO:gurobipy:Model fingerprint: 0xc5c44c72

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 5e+02]

INFO:gurobipy:  Bounds range     [4e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23623 rows and 3288 columns

INFO:gurobipy:Presolve removed 23623 rows and 3288 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1194 rows, 8760 columns, 17296 nonzeros

INFO:gurobipy:Presolved: 1194 rows, 8760 columns, 17296 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.304e+03

INFO:gurobipy: AA' NZ     : 3.304e+03

 Factor NZ  : 2.797e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.797e+04 (roughly 4 MB of memory)

 Factor Ops : 9.706e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.706e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.68266695e+11 -3.46437068e+12  2.13e+06 5.94e+01  3.77e+09     0s

INFO:gurobipy:   0   2.68266695e+11 -3.46437068e+12  2.13e+06 5.94e+01  3.77e+09     0s

   1   3.06550215e+10 -9.16732623e+11  1.66e+05 4.62e-11  3.22e+08     0s

INFO:gurobipy:   1   3.06550215e+10 -9.16732623e+11  1.66e+05 4.62e-11  3.22e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1463    1.5141130e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1463    1.5141130e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1463 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1463 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.514112975e+09

INFO:gurobipy:Optimal objective  1.514112975e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.51e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-07 00:00:00:2019-04-12 21:00:00] (17/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 90.45it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 219.14it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-31ko5u5g.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-31ko5u5g.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xd410d31b

INFO:gurobipy:Model fingerprint: 0xd410d31b

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [5e+02, 5e+02]

INFO:gurobipy:  Bounds range     [5e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23623 rows and 3277 columns

INFO:gurobipy:Presolve removed 23623 rows and 3277 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1194 rows, 8771 columns, 17307 nonzeros

INFO:gurobipy:Presolved: 1194 rows, 8771 columns, 17307 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.304e+03

INFO:gurobipy: AA' NZ     : 3.304e+03

 Factor NZ  : 2.797e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.797e+04 (roughly 4 MB of memory)

 Factor Ops : 9.706e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.706e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.70183363e+11 -3.48540292e+12  2.15e+06 5.93e+01  3.80e+09     0s

INFO:gurobipy:   0   2.70183363e+11 -3.48540292e+12  2.15e+06 5.93e+01  3.80e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1519    1.3537732e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1519    1.3537732e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1519 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1519 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.353773241e+09

INFO:gurobipy:Optimal objective  1.353773241e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.35e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-13 00:00:00:2019-04-18 21:00:00] (18/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.07it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 255.94it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-epirft8a.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-epirft8a.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x9be75271

INFO:gurobipy:Model fingerprint: 0x9be75271

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [4e+02, 5e+02]

INFO:gurobipy:  Bounds range     [4e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23624 rows and 3294 columns

INFO:gurobipy:Presolve removed 23624 rows and 3294 columns

Presolve time: 0.16s

INFO:gurobipy:Presolve time: 0.16s

Presolved: 1193 rows, 8754 columns, 17277 nonzeros

INFO:gurobipy:Presolved: 1193 rows, 8754 columns, 17277 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.303e+03

INFO:gurobipy: AA' NZ     : 3.303e+03

 Factor NZ  : 2.822e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.822e+04 (roughly 4 MB of memory)

 Factor Ops : 1.045e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.045e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.73718702e+11 -3.50002132e+12  1.45e+06 3.15e+02  2.45e+09     0s

INFO:gurobipy:   0   1.73718702e+11 -3.50002132e+12  1.45e+06 3.15e+02  2.45e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.21 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.21 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1549    1.0578044e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1549    1.0578044e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1549 iterations and 0.23 seconds (0.04 work units)

INFO:gurobipy:Solved in 1549 iterations and 0.23 seconds (0.04 work units)

Optimal objective  1.057804370e+09

INFO:gurobipy:Optimal objective  1.057804370e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.06e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-19 00:00:00:2019-04-24 21:00:00] (19/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.91it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 248.63it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-slcqsqwj.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-slcqsqwj.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xff99f832

INFO:gurobipy:Model fingerprint: 0xff99f832

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23626 rows and 3446 columns

INFO:gurobipy:Presolve removed 23626 rows and 3446 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1191 rows, 8602 columns, 17003 nonzeros

INFO:gurobipy:Presolved: 1191 rows, 8602 columns, 17003 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.301e+03

INFO:gurobipy: AA' NZ     : 3.301e+03

 Factor NZ  : 2.816e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.816e+04 (roughly 4 MB of memory)

 Factor Ops : 9.976e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.976e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

Barrier performed 0 iterations in 0.21 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.21 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1411    9.6624189e+08   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1411    9.6624189e+08   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1411 iterations and 0.26 seconds (0.04 work units)

INFO:gurobipy:Solved in 1411 iterations and 0.26 seconds (0.04 work units)

Optimal objective  9.662418927e+08

INFO:gurobipy:Optimal objective  9.662418927e+08
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 9.66e+08
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-04-25 00:00:00:2019-04-30 21:00:00] (20/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.83it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.80it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-wnbur7ic.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-wnbur7ic.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xc15b8037

INFO:gurobipy:Model fingerprint: 0xc15b8037

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23628 rows and 3331 columns

INFO:gurobipy:Presolve removed 23628 rows and 3331 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1189 rows, 8717 columns, 17208 nonzeros

INFO:gurobipy:Presolved: 1189 rows, 8717 columns, 17208 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.299e+03

INFO:gurobipy: AA' NZ     : 3.299e+03

 Factor NZ  : 2.825e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.825e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.21775609e+11 -3.62610300e+12  2.41e+06 2.44e+02  3.13e+09     0s

INFO:gurobipy:   0   2.21775609e+11 -3.62610300e+12  2.41e+06 2.44e+02  3.13e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1463    1.2283347e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1463    1.2283347e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1463 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1463 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.228334653e+09

INFO:gurobipy:Optimal objective  1.228334653e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.23e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-01 00:00:00:2019-05-06 21:00:00] (21/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.33it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.57it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3aroiwzw.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-3aroiwzw.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x7778f4fe

INFO:gurobipy:Model fingerprint: 0x7778f4fe

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23628 rows and 3266 columns

INFO:gurobipy:Presolve removed 23628 rows and 3266 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1189 rows, 8782 columns, 17313 nonzeros

INFO:gurobipy:Presolved: 1189 rows, 8782 columns, 17313 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.299e+03

INFO:gurobipy: AA' NZ     : 3.299e+03

 Factor NZ  : 2.825e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.825e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.21862904e+11 -3.65728963e+12  2.40e+06 5.77e+01  3.13e+09     0s

INFO:gurobipy:   0   2.21862904e+11 -3.65728963e+12  2.40e+06 5.77e+01  3.13e+09     0s

   1   2.69849057e+10 -8.14016181e+11  1.90e+05 4.72e-11  2.70e+08     0s

INFO:gurobipy:   1   2.69849057e+10 -8.14016181e+11  1.90e+05 4.72e-11  2.70e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1658    1.0999415e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1658    1.0999415e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1658 iterations and 0.14 seconds (0.05 work units)

INFO:gurobipy:Solved in 1658 iterations and 0.14 seconds (0.05 work units)

Optimal objective  1.099941461e+09

INFO:gurobipy:Optimal objective  1.099941461e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.10e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-07 00:00:00:2019-05-12 21:00:00] (22/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 89.26it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 248.09it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8qf00p3n.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8qf00p3n.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x6046798b

INFO:gurobipy:Model fingerprint: 0x6046798b

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23630 rows and 3262 columns

INFO:gurobipy:Presolve removed 23630 rows and 3262 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1187 rows, 8786 columns, 17315 nonzeros

INFO:gurobipy:Presolved: 1187 rows, 8786 columns, 17315 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.297e+03

INFO:gurobipy: AA' NZ     : 3.297e+03

 Factor NZ  : 2.747e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.747e+04 (roughly 4 MB of memory)

 Factor Ops : 9.053e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.053e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.45874557e+11 -3.99917847e+12  4.27e+06 6.62e+01  4.90e+09     0s

INFO:gurobipy:   0   3.45874557e+11 -3.99917847e+12  4.27e+06 6.62e+01  4.90e+09     0s

   1   3.74664151e+10 -1.03057616e+12  3.33e+05 5.38e-11  4.15e+08     0s

INFO:gurobipy:   1   3.74664151e+10 -1.03057616e+12  3.33e+05 5.38e-11  4.15e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1556    1.2344181e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1556    1.2344181e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1556 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1556 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.234418124e+09

INFO:gurobipy:Optimal objective  1.234418124e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.23e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-13 00:00:00:2019-05-18 21:00:00] (23/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 90.36it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.74it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-coyc5kk4.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-coyc5kk4.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xe0dad1d5

INFO:gurobipy:Model fingerprint: 0xe0dad1d5

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23630 rows and 3281 columns

INFO:gurobipy:Presolve removed 23630 rows and 3281 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1187 rows, 8767 columns, 17265 nonzeros

INFO:gurobipy:Presolved: 1187 rows, 8767 columns, 17265 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.297e+03

INFO:gurobipy: AA' NZ     : 3.297e+03

 Factor NZ  : 2.747e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.747e+04 (roughly 4 MB of memory)

 Factor Ops : 9.053e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.053e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.40245557e+11 -3.99155931e+12  2.91e+06 3.31e+02  3.41e+09     0s

INFO:gurobipy:   0   2.40245557e+11 -3.99155931e+12  2.91e+06 3.31e+02  3.41e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1600    1.1613519e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1600    1.1613519e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1600 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1600 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.161351941e+09

INFO:gurobipy:Optimal objective  1.161351941e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.16e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-19 00:00:00:2019-05-24 21:00:00] (24/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 88.32it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 246.15it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-go535z_1.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-go535z_1.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x091da68f

INFO:gurobipy:Model fingerprint: 0x091da68f

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 5e+02]

INFO:gurobipy:  Bounds range     [2e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23631 rows and 3403 columns

INFO:gurobipy:Presolve removed 23631 rows and 3403 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1186 rows, 8645 columns, 17048 nonzeros

INFO:gurobipy:Presolved: 1186 rows, 8645 columns, 17048 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.296e+03

INFO:gurobipy: AA' NZ     : 3.296e+03

 Factor NZ  : 2.709e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.709e+04 (roughly 4 MB of memory)

 Factor Ops : 9.323e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.323e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.20358663e+11 -3.92726655e+12  2.82e+06 3.16e+02  3.15e+09     0s

INFO:gurobipy:   0   2.20358663e+11 -3.92726655e+12  2.82e+06 3.16e+02  3.15e+09     0s

   1   3.08246204e+10 -8.77721301e+11  2.68e+05 6.06e-11  3.18e+08     0s

INFO:gurobipy:   1   3.08246204e+10 -8.77721301e+11  2.68e+05 6.06e-11  3.18e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1406    1.0397846e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1406    1.0397846e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1406 iterations and 0.16 seconds (0.05 work units)

INFO:gurobipy:Solved in 1406 iterations and 0.16 seconds (0.05 work units)

Optimal objective  1.039784588e+09

INFO:gurobipy:Optimal objective  1.039784588e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.04e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-25 00:00:00:2019-05-30 21:00:00] (25/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.15it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 258.80it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-f8al0jl6.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-f8al0jl6.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xbb044ce2

INFO:gurobipy:Model fingerprint: 0xbb044ce2

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 5e+02]

INFO:gurobipy:  Bounds range     [3e+02, 5e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23629 rows and 3386 columns

INFO:gurobipy:Presolve removed 23629 rows and 3386 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1188 rows, 8662 columns, 17072 nonzeros

INFO:gurobipy:Presolved: 1188 rows, 8662 columns, 17072 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.298e+03

INFO:gurobipy: AA' NZ     : 3.298e+03

 Factor NZ  : 2.835e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.835e+04 (roughly 4 MB of memory)

 Factor Ops : 1.082e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.082e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.26987982e+11 -3.99629868e+12  2.64e+06 3.07e+02  3.25e+09     0s

INFO:gurobipy:   0   2.26987982e+11 -3.99629868e+12  2.64e+06 3.07e+02  3.25e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1527    1.0557460e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1527    1.0557460e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1527 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1527 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.055746012e+09

INFO:gurobipy:Optimal objective  1.055746012e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.06e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-05-31 00:00:00:2019-06-05 21:00:00] (26/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 91.45it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 260.63it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8ujj6pzx.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-8ujj6pzx.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x559b7221

INFO:gurobipy:Model fingerprint: 0x559b7221

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 4e+02]

INFO:gurobipy:  Bounds range     [3e+02, 4e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23625 rows and 3509 columns

INFO:gurobipy:Presolve removed 23625 rows and 3509 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1192 rows, 8539 columns, 16833 nonzeros

INFO:gurobipy:Presolved: 1192 rows, 8539 columns, 16833 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.302e+03

INFO:gurobipy: AA' NZ     : 3.302e+03

 Factor NZ  : 2.710e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.710e+04 (roughly 4 MB of memory)

 Factor Ops : 8.831e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 8.831e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.37646470e+11 -4.09193474e+12  2.20e+06 3.37e+02  3.39e+09     0s

INFO:gurobipy:   0   2.37646470e+11 -4.09193474e+12  2.20e+06 3.37e+02  3.39e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1479    1.0057262e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1479    1.0057262e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1479 iterations and 0.15 seconds (0.04 work units)

INFO:gurobipy:Solved in 1479 iterations and 0.15 seconds (0.04 work units)

Optimal objective  1.005726189e+09

INFO:gurobipy:Optimal objective  1.005726189e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.01e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-06 00:00:00:2019-06-11 21:00:00] (27/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 88.74it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 57.60it/s]
INFO:linopy.io: Writing time: 0.36s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ba2pk15p.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ba2pk15p.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xadc00012

INFO:gurobipy:Model fingerprint: 0xadc00012

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23620 rows and 3506 columns

INFO:gurobipy:Presolve removed 23620 rows and 3506 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1197 rows, 8542 columns, 16841 nonzeros

INFO:gurobipy:Presolved: 1197 rows, 8542 columns, 16841 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.307e+03

INFO:gurobipy: AA' NZ     : 3.307e+03

 Factor NZ  : 2.828e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.828e+04 (roughly 4 MB of memory)

 Factor Ops : 1.009e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.009e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   3.05233298e+11 -4.16497340e+12  2.03e+06 2.66e+02  4.34e+09     0s

INFO:gurobipy:   0   3.05233298e+11 -4.16497340e+12  2.03e+06 2.66e+02  4.34e+09     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1506    1.0249730e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1506    1.0249730e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1506 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1506 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.024972982e+09

INFO:gurobipy:Optimal objective  1.024972982e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.02e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-12 00:00:00:2019-06-17 21:00:00] (28/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 92.07it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.24it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5j1l3ubz.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5j1l3ubz.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x2054356d

INFO:gurobipy:Model fingerprint: 0x2054356d

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [3e+02, 3e+02]

INFO:gurobipy:  Bounds range     [3e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23617 rows and 3565 columns

INFO:gurobipy:Presolve removed 23617 rows and 3565 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1200 rows, 8483 columns, 16717 nonzeros

INFO:gurobipy:Presolved: 1200 rows, 8483 columns, 16717 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.310e+03

INFO:gurobipy: AA' NZ     : 3.310e+03

 Factor NZ  : 2.864e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.864e+04 (roughly 4 MB of memory)

 Factor Ops : 1.084e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.084e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   2.81356444e+11 -4.14913142e+12  1.90e+06 3.44e+02  4.00e+09     0s

INFO:gurobipy:   0   2.81356444e+11 -4.14913142e+12  1.90e+06 3.44e+02  4.00e+09     0s

   1   3.95351230e+10 -8.97728952e+11  1.86e+05 5.67e-11  4.09e+08     0s

INFO:gurobipy:   1   3.95351230e+10 -8.97728952e+11  1.86e+05 5.67e-11  4.09e+08     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1538    1.0244298e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1538    1.0244298e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1538 iterations and 0.18 seconds (0.05 work units)

INFO:gurobipy:Solved in 1538 iterations and 0.18 seconds (0.05 work units)

Optimal objective  1.024429778e+09

INFO:gurobipy:Optimal objective  1.024429778e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.02e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-18 00:00:00:2019-06-23 21:00:00] (29/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.13it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.79it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-azss6zml.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-azss6zml.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xf4b06be0

INFO:gurobipy:Model fingerprint: 0xf4b06be0

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 3e+02]

INFO:gurobipy:  Bounds range     [2e+02, 3e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3581 columns

INFO:gurobipy:Presolve removed 23611 rows and 3581 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 1206 rows, 8467 columns, 16679 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8467 columns, 16679 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1534    1.0821683e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1534    1.0821683e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1534 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1534 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.082168323e+09

INFO:gurobipy:Optimal objective  1.082168323e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.08e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-24 00:00:00:2019-06-29 21:00:00] (30/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 90.29it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 245.61it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5nmm27px.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-5nmm27px.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x28fd23b6

INFO:gurobipy:Model fingerprint: 0x28fd23b6

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3581 columns

INFO:gurobipy:Presolve removed 23611 rows and 3581 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1206 rows, 8467 columns, 16679 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8467 columns, 16679 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   8.09836520e+11 -4.47776181e+12  5.75e+06 3.69e+02  1.14e+10     0s

INFO:gurobipy:   0   8.09836520e+11 -4.47776181e+12  5.75e+06 3.69e+02  1.14e+10     0s

   1   1.15807343e+11 -1.71431763e+12  6.99e+05 6.40e-11  1.43e+09     0s

INFO:gurobipy:   1   1.15807343e+11 -1.71431763e+12  6.99e+05 6.40e-11  1.43e+09     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1637    1.0376449e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1637    1.0376449e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1637 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1637 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.037644922e+09

INFO:gurobipy:Optimal objective  1.037644922e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.04e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-06-30 00:00:00:2019-07-05 21:00:00] (31/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.32it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.69it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-a4gq4vza.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-a4gq4vza.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x61ccc280

INFO:gurobipy:Model fingerprint: 0x61ccc280

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23611 rows and 3575 columns

INFO:gurobipy:Presolve removed 23611 rows and 3575 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1206 rows, 8473 columns, 16691 nonzeros

INFO:gurobipy:Presolved: 1206 rows, 8473 columns, 16691 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.316e+03

INFO:gurobipy: AA' NZ     : 3.316e+03

 Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.803e+04 (roughly 4 MB of memory)

 Factor Ops : 9.827e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 9.827e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.56361893e+12 -5.08603636e+12  1.12e+07 3.87e+02  2.20e+10     0s

INFO:gurobipy:   0   1.56361893e+12 -5.08603636e+12  1.12e+07 3.87e+02  2.20e+10     0s

   1   3.41484042e+11 -2.55185513e+12  2.27e+06 5.06e-11  4.50e+09     0s

INFO:gurobipy:   1   3.41484042e+11 -2.55185513e+12  2.27e+06 5.06e-11  4.50e+09     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1608    1.0096439e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1608    1.0096439e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1608 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1608 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.009643917e+09

INFO:gurobipy:Optimal objective  1.009643917e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.01e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-06 00:00:00:2019-07-11 21:00:00] (32/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.09it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.52it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nzxqwsqr.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-nzxqwsqr.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xd86fe5a1

INFO:gurobipy:Model fingerprint: 0xd86fe5a1

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23609 rows and 3501 columns

INFO:gurobipy:Presolve removed 23609 rows and 3501 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1208 rows, 8547 columns, 19878 nonzeros

INFO:gurobipy:Presolved: 1208 rows, 8547 columns, 19878 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.949e+03

INFO:gurobipy: AA' NZ     : 3.949e+03

 Factor NZ  : 2.906e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.906e+04 (roughly 4 MB of memory)

 Factor Ops : 1.062e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.062e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.04974186e+13 -8.97955070e+12  9.37e+08 3.71e+02  1.48e+11     0s

INFO:gurobipy:   0   1.04974186e+13 -8.97955070e+12  9.37e+08 3.71e+02  1.48e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1432    1.1449748e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1432    1.1449748e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1432 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1432 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.144974846e+09

INFO:gurobipy:Optimal objective  1.144974846e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.14e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-12 00:00:00:2019-07-17 21:00:00] (33/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 85.04it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 233.46it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-a6oh1pkw.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-a6oh1pkw.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xb77e6761

INFO:gurobipy:Model fingerprint: 0xb77e6761

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3602 columns

INFO:gurobipy:Presolve removed 23608 rows and 3602 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8446 columns, 19694 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8446 columns, 19694 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 3.023e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 3.023e+04 (roughly 4 MB of memory)

 Factor Ops : 1.201e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.201e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.14509967e+13 -1.04439839e+13  6.44e+08 3.80e+02  1.61e+11     0s

INFO:gurobipy:   0   1.14509967e+13 -1.04439839e+13  6.44e+08 3.80e+02  1.61e+11     0s

   1   1.07059478e+12 -7.59072053e+12  5.75e+07 1.12e+04  1.50e+10     0s

INFO:gurobipy:   1   1.07059478e+12 -7.59072053e+12  5.75e+07 1.12e+04  1.50e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1482    1.1936193e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1482    1.1936193e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1482 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1482 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.193619328e+09

INFO:gurobipy:Optimal objective  1.193619328e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.19e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-18 00:00:00:2019-07-23 21:00:00] (34/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 88.79it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 252.47it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-1xbjbrjr.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-1xbjbrjr.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x2144fa79

INFO:gurobipy:Model fingerprint: 0x2144fa79

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3599 columns

INFO:gurobipy:Presolve removed 23608 rows and 3599 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8449 columns, 19697 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8449 columns, 19697 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.09238736e+13 -1.04469918e+13  4.60e+08 3.75e+02  1.53e+11     0s

INFO:gurobipy:   0   1.09238736e+13 -1.04469918e+13  4.60e+08 3.75e+02  1.53e+11     0s

   1   1.27618863e+12 -7.66736204e+12  5.17e+07 1.25e+04  1.79e+10     0s

INFO:gurobipy:   1   1.27618863e+12 -7.66736204e+12  5.17e+07 1.25e+04  1.79e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1543    1.1041420e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1543    1.1041420e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1543 iterations and 0.21 seconds (0.05 work units)

INFO:gurobipy:Solved in 1543 iterations and 0.21 seconds (0.05 work units)

Optimal objective  1.104141981e+09

INFO:gurobipy:Optimal objective  1.104141981e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.10e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-24 00:00:00:2019-07-29 21:00:00] (35/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 63.44it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 240.86it/s]
INFO:linopy.io: Writing time: 0.33s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mf7fuju_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-mf7fuju_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xf8f0aab2

INFO:gurobipy:Model fingerprint: 0xf8f0aab2

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 5e+00]

INFO:gurobipy:  Matrix range     [8e-03, 5e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3583 columns

INFO:gurobipy:Presolve removed 23608 rows and 3583 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8465 columns, 19713 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8465 columns, 19713 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.10563583e+13 -1.04532680e+13  4.66e+08 3.76e+02  1.55e+11     0s

INFO:gurobipy:   0   1.10563583e+13 -1.04532680e+13  4.66e+08 3.76e+02  1.55e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1596    1.0773282e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1596    1.0773282e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1596 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1596 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.077328181e+09

INFO:gurobipy:Optimal objective  1.077328181e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.08e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-07-30 00:00:00:2019-08-04 21:00:00] (36/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.08it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.36it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6c_kml2j.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-6c_kml2j.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x9c3a76f6

INFO:gurobipy:Model fingerprint: 0x9c3a76f6

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3607 columns

INFO:gurobipy:Presolve removed 23608 rows and 3607 columns

Presolve time: 0.08s

INFO:gurobipy:Presolve time: 0.08s

Presolved: 1209 rows, 8441 columns, 19689 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8441 columns, 19689 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.11644184e+13 -1.04371831e+13  4.70e+08 4.11e+02  1.57e+11     0s

INFO:gurobipy:   0   1.11644184e+13 -1.04371831e+13  4.70e+08 4.11e+02  1.57e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1498    1.2932538e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1498    1.2932538e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1498 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1498 iterations and 0.13 seconds (0.05 work units)

Optimal objective  1.293253761e+09

INFO:gurobipy:Optimal objective  1.293253761e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.29e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-05 00:00:00:2019-08-10 21:00:00] (37/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 64.05it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.52it/s]
INFO:linopy.io: Writing time: 0.32s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-db_hsw1a.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-db_hsw1a.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x149fcd44

INFO:gurobipy:Model fingerprint: 0x149fcd44

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3610 columns

INFO:gurobipy:Presolve removed 23608 rows and 3610 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8438 columns, 19686 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8438 columns, 19686 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.13574171e+13 -1.04240298e+13  4.79e+08 4.00e+02  1.59e+11     0s

INFO:gurobipy:   0   1.13574171e+13 -1.04240298e+13  4.79e+08 4.00e+02  1.59e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1540    1.0814780e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1540    1.0814780e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1540 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1540 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.081477958e+09

INFO:gurobipy:Optimal objective  1.081477958e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.08e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-11 00:00:00:2019-08-16 21:00:00] (38/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.75it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 223.82it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7omnycas.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7omnycas.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x909d9598

INFO:gurobipy:Model fingerprint: 0x909d9598

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3628 columns

INFO:gurobipy:Presolve removed 23608 rows and 3628 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.14993421e+13 -1.04428901e+13  4.85e+08 3.46e+02  1.61e+11     0s

INFO:gurobipy:   0   1.14993421e+13 -1.04428901e+13  4.85e+08 3.46e+02  1.61e+11     0s

   1   1.14792501e+12 -7.99245239e+12  4.65e+07 1.21e+04  1.61e+10     0s

INFO:gurobipy:   1   1.14792501e+12 -7.99245239e+12  4.65e+07 1.21e+04  1.61e+10     0s

   2   1.11242240e+11 -2.31603845e+12  3.81e+06 8.77e-11  1.42e+09     0s

INFO:gurobipy:   2   1.11242240e+11 -2.31603845e+12  3.81e+06 8.77e-11  1.42e+09     0s

INFO:gurobipy:

Barrier performed 2 iterations in 0.10 seconds (0.04 work units)

INFO:gurobipy:Barrier performed 2 iterations in 0.10 seconds (0.04 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1637    1.0117764e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1637    1.0117764e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1637 iterations and 0.13 seconds (0.06 work units)

INFO:gurobipy:Solved in 1637 iterations and 0.13 seconds (0.06 work units)

Optimal objective  1.011776443e+09

INFO:gurobipy:Optimal objective  1.011776443e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.01e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-17 00:00:00:2019-08-22 21:00:00] (39/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 91.63it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.09it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2k4rw883.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2k4rw883.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x3ab93a44

INFO:gurobipy:Model fingerprint: 0x3ab93a44

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3628 columns

INFO:gurobipy:Presolve removed 23608 rows and 3628 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.16296934e+13 -1.04361042e+13  4.90e+08 3.47e+02  1.63e+11     0s

INFO:gurobipy:   0   1.16296934e+13 -1.04361042e+13  4.90e+08 3.47e+02  1.63e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1661    1.0412254e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1661    1.0412254e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1661 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1661 iterations and 0.13 seconds (0.05 work units)

Optimal objective  1.041225431e+09

INFO:gurobipy:Optimal objective  1.041225431e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.04e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-23 00:00:00:2019-08-28 21:00:00] (40/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.13it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.52it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-kmj_nd5_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-kmj_nd5_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x16f81183

INFO:gurobipy:Model fingerprint: 0x16f81183

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3628 columns

INFO:gurobipy:Presolve removed 23608 rows and 3628 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8420 columns, 19668 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.17481786e+13 -1.04460396e+13  4.95e+08 3.42e+02  1.65e+11     0s

INFO:gurobipy:   0   1.17481786e+13 -1.04460396e+13  4.95e+08 3.42e+02  1.65e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1601    1.1446940e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1601    1.1446940e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1601 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1601 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.144694022e+09

INFO:gurobipy:Optimal objective  1.144694022e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.14e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-08-29 00:00:00:2019-09-03 21:00:00] (41/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 84.32it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.45it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x2_rpjxn.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-x2_rpjxn.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xf4329727

INFO:gurobipy:Model fingerprint: 0xf4329727

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3650 columns

INFO:gurobipy:Presolve removed 23608 rows and 3650 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8398 columns, 19646 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8398 columns, 19646 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.18877406e+13 -1.04374468e+13  5.01e+08 3.35e+02  1.67e+11     0s

INFO:gurobipy:   0   1.18877406e+13 -1.04374468e+13  5.01e+08 3.35e+02  1.67e+11     0s

   1   1.31709684e+12 -8.07236915e+12  5.36e+07 1.28e+04  1.85e+10     0s

INFO:gurobipy:   1   1.31709684e+12 -8.07236915e+12  5.36e+07 1.28e+04  1.85e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1605    1.0803728e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1605    1.0803728e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1605 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1605 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.080372810e+09

INFO:gurobipy:Optimal objective  1.080372810e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.08e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-04 00:00:00:2019-09-09 21:00:00] (42/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 94.27it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 254.04it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ypfxp8vg.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ypfxp8vg.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x68ee1c52

INFO:gurobipy:Model fingerprint: 0x68ee1c52

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3452 columns

INFO:gurobipy:Presolve removed 23608 rows and 3452 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8596 columns, 20064 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8596 columns, 20064 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1380    1.3618740e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1380    1.3618740e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1380 iterations and 0.25 seconds (0.05 work units)

INFO:gurobipy:Solved in 1380 iterations and 0.25 seconds (0.05 work units)

Optimal objective  1.361873953e+09

INFO:gurobipy:Optimal objective  1.361873953e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.36e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-10 00:00:00:2019-09-15 21:00:00] (43/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 95.37it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.69it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ayz9hz9q.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ayz9hz9q.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x60b327c0

INFO:gurobipy:Model fingerprint: 0x60b327c0

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [8e+01, 1e+02]

INFO:gurobipy:  Bounds range     [8e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3538 columns

INFO:gurobipy:Presolve removed 23608 rows and 3538 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8510 columns, 19860 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8510 columns, 19860 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.21402165e+13 -1.04650956e+13  5.12e+08 3.39e+02  1.71e+11     0s

INFO:gurobipy:   0   1.21402165e+13 -1.04650956e+13  5.12e+08 3.39e+02  1.71e+11     0s

   1   1.21228501e+12 -7.98787361e+12  4.96e+07 1.20e+04  1.72e+10     0s

INFO:gurobipy:   1   1.21228501e+12 -7.98787361e+12  4.96e+07 1.20e+04  1.72e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1653    1.0069401e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1653    1.0069401e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1653 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1653 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.006940136e+09

INFO:gurobipy:Optimal objective  1.006940136e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.01e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-16 00:00:00:2019-09-21 21:00:00] (44/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.74it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 251.69it/s]
INFO:linopy.io: Writing time: 0.27s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ea73yasm.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ea73yasm.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12042 columns, 48950 nonzeros

INFO:gurobipy:obj: 24817 rows, 12042 columns, 48950 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12042 columns and 48950 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12042 columns and 48950 nonzeros

Model fingerprint: 0x46891296

INFO:gurobipy:Model fingerprint: 0x46891296

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+01, 8e+01]

INFO:gurobipy:  Bounds range     [2e+01, 8e+01]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23612 rows and 3354 columns

INFO:gurobipy:Presolve removed 23612 rows and 3354 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1205 rows, 8688 columns, 20229 nonzeros

INFO:gurobipy:Presolved: 1205 rows, 8688 columns, 20229 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.948e+03

INFO:gurobipy: AA' NZ     : 3.948e+03

 Factor NZ  : 2.842e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.842e+04 (roughly 4 MB of memory)

 Factor Ops : 1.027e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.027e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.24097934e+13 -1.04922197e+13  5.21e+08 3.32e+02  1.76e+11     0s

INFO:gurobipy:   0   1.24097934e+13 -1.04922197e+13  5.21e+08 3.32e+02  1.76e+11     0s

   1   1.19612106e+12 -7.95044187e+12  4.92e+07 1.14e+04  1.71e+10     0s

INFO:gurobipy:   1   1.19612106e+12 -7.95044187e+12  4.92e+07 1.14e+04  1.71e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1611    1.1577855e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1611    1.1577855e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1611 iterations and 0.14 seconds (0.06 work units)

INFO:gurobipy:Solved in 1611 iterations and 0.14 seconds (0.06 work units)

Optimal objective  1.157785548e+09

INFO:gurobipy:Optimal objective  1.157785548e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12042 primals, 24817 duals
Objective: 1.16e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-22 00:00:00:2019-09-27 21:00:00] (45/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.42it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 261.23it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-r6isgrrj.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-r6isgrrj.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12041 columns, 48949 nonzeros

INFO:gurobipy:obj: 24817 rows, 12041 columns, 48949 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12041 columns and 48949 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12041 columns and 48949 nonzeros

Model fingerprint: 0x95d1b40f

INFO:gurobipy:Model fingerprint: 0x95d1b40f

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+01, 1e+02]

INFO:gurobipy:  Bounds range     [2e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23614 rows and 3581 columns

INFO:gurobipy:Presolve removed 23614 rows and 3581 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1203 rows, 8460 columns, 19786 nonzeros

INFO:gurobipy:Presolved: 1203 rows, 8460 columns, 19786 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.946e+03

INFO:gurobipy: AA' NZ     : 3.946e+03

 Factor NZ  : 2.912e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.912e+04 (roughly 4 MB of memory)

 Factor Ops : 1.036e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.036e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.24615742e+13 -1.04381761e+13  5.25e+08 3.49e+02  1.75e+11     0s

INFO:gurobipy:   0   1.24615742e+13 -1.04381761e+13  5.25e+08 3.49e+02  1.75e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.06 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1407    1.3164518e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1407    1.3164518e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1407 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1407 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.316451841e+09

INFO:gurobipy:Optimal objective  1.316451841e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12041 primals, 24817 duals
Objective: 1.32e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-09-28 00:00:00:2019-10-03 21:00:00] (46/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 81.49it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 253.28it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-v3v_d26v.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-v3v_d26v.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x9127e505

INFO:gurobipy:Model fingerprint: 0x9127e505

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [9e+01, 1e+02]

INFO:gurobipy:  Bounds range     [9e+01, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3438 columns

INFO:gurobipy:Presolve removed 23608 rows and 3438 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8610 columns, 20063 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8610 columns, 20063 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.27144851e+13 -1.04528194e+13  5.34e+08 3.46e+02  1.79e+11     0s

INFO:gurobipy:   0   1.27144851e+13 -1.04528194e+13  5.34e+08 3.46e+02  1.79e+11     0s

   1   1.13605610e+12 -7.96901985e+12  4.69e+07 1.21e+04  1.63e+10     0s

INFO:gurobipy:   1   1.13605610e+12 -7.96901985e+12  4.69e+07 1.21e+04  1.63e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1726    1.0256804e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1726    1.0256804e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1726 iterations and 0.11 seconds (0.06 work units)

INFO:gurobipy:Solved in 1726 iterations and 0.11 seconds (0.06 work units)

Optimal objective  1.025680364e+09

INFO:gurobipy:Optimal objective  1.025680364e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.03e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-04 00:00:00:2019-10-09 21:00:00] (47/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 77.97it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 255.98it/s]
INFO:linopy.io: Writing time: 0.27s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4_i0g71y.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-4_i0g71y.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xafe90362

INFO:gurobipy:Model fingerprint: 0xafe90362

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3288 columns

INFO:gurobipy:Presolve removed 23608 rows and 3288 columns

Presolve time: 0.07s

INFO:gurobipy:Presolve time: 0.07s

Presolved: 1209 rows, 8760 columns, 20344 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8760 columns, 20344 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.29167456e+13 -1.04814658e+13  5.38e+08 6.06e+01  1.82e+11     0s

INFO:gurobipy:   0   1.29167456e+13 -1.04814658e+13  5.38e+08 6.06e+01  1.82e+11     0s

   1   1.12544478e+12 -8.00370044e+12  4.64e+07 1.22e+04  1.62e+10     0s

INFO:gurobipy:   1   1.12544478e+12 -8.00370044e+12  4.64e+07 1.22e+04  1.62e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1678    1.2141513e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1678    1.2141513e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1678 iterations and 0.19 seconds (0.06 work units)

INFO:gurobipy:Solved in 1678 iterations and 0.19 seconds (0.06 work units)

Optimal objective  1.214151312e+09

INFO:gurobipy:Optimal objective  1.214151312e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.21e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-10 00:00:00:2019-10-15 21:00:00] (48/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 89.59it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 248.07it/s]
INFO:linopy.io: Writing time: 0.24s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-lq2fu4et.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-lq2fu4et.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xb3001cc7

INFO:gurobipy:Model fingerprint: 0xb3001cc7

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3479 columns

INFO:gurobipy:Presolve removed 23608 rows and 3479 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8569 columns, 19987 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8569 columns, 19987 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.28416083e+13 -1.04668956e+13  5.41e+08 4.10e+02  1.81e+11     0s

INFO:gurobipy:   0   1.28416083e+13 -1.04668956e+13  5.41e+08 4.10e+02  1.81e+11     0s

   1   1.24102918e+12 -8.01749914e+12  5.07e+07 1.24e+04  1.76e+10     0s

INFO:gurobipy:   1   1.24102918e+12 -8.01749914e+12  5.07e+07 1.24e+04  1.76e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1727    9.9613544e+08   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1727    9.9613544e+08   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1727 iterations and 0.14 seconds (0.06 work units)

INFO:gurobipy:Solved in 1727 iterations and 0.14 seconds (0.06 work units)

Optimal objective  9.961354352e+08

INFO:gurobipy:Optimal objective  9.961354352e+08
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 9.96e+08
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-16 00:00:00:2019-10-21 21:00:00] (49/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 85.44it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.89it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-9j96crr9.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-9j96crr9.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xbe8b6e51

INFO:gurobipy:Model fingerprint: 0xbe8b6e51

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3360 columns

INFO:gurobipy:Presolve removed 23608 rows and 3360 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8688 columns, 20228 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8688 columns, 20228 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.29657417e+13 -1.04581827e+13  5.46e+08 2.60e+02  1.84e+11     0s

INFO:gurobipy:   0   1.29657417e+13 -1.04581827e+13  5.46e+08 2.60e+02  1.84e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1531    1.2806883e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1531    1.2806883e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1531 iterations and 0.14 seconds (0.05 work units)

INFO:gurobipy:Solved in 1531 iterations and 0.14 seconds (0.05 work units)

Optimal objective  1.280688269e+09

INFO:gurobipy:Optimal objective  1.280688269e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.28e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-22 00:00:00:2019-10-27 21:00:00] (50/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.68it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.72it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-z6g4irhw.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-z6g4irhw.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xde54f45a

INFO:gurobipy:Model fingerprint: 0xde54f45a

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3354 columns

INFO:gurobipy:Presolve removed 23608 rows and 3354 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1209 rows, 8694 columns, 20244 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8694 columns, 20244 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.31001029e+13 -1.04683734e+13  5.52e+08 2.83e+02  1.86e+11     0s

INFO:gurobipy:   0   1.31001029e+13 -1.04683734e+13  5.52e+08 2.83e+02  1.86e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1521    1.2059049e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1521    1.2059049e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1521 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1521 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.205904855e+09

INFO:gurobipy:Optimal objective  1.205904855e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.21e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-10-28 00:00:00:2019-11-02 21:00:00] (51/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.82it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 219.80it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qe1hg4fv.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-qe1hg4fv.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x009cdc0f

INFO:gurobipy:Model fingerprint: 0x009cdc0f

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3305 columns

INFO:gurobipy:Presolve removed 23608 rows and 3305 columns

Presolve time: 0.06s

INFO:gurobipy:Presolve time: 0.06s

Presolved: 1209 rows, 8743 columns, 20327 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8743 columns, 20327 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.01s

INFO:gurobipy:Ordering time: 0.01s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.34519848e+13 -1.04736392e+13  5.58e+08 5.94e+01  1.89e+11     0s

INFO:gurobipy:   0   1.34519848e+13 -1.04736392e+13  5.58e+08 5.94e+01  1.89e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.11 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1538    1.8262336e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1538    1.8262336e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1538 iterations and 0.14 seconds (0.05 work units)

INFO:gurobipy:Solved in 1538 iterations and 0.14 seconds (0.05 work units)

Optimal objective  1.826233576e+09

INFO:gurobipy:Optimal objective  1.826233576e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.83e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-03 00:00:00:2019-11-08 21:00:00] (52/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 78.08it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.22it/s]
INFO:linopy.io: Writing time: 0.28s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2hytrpwm.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2hytrpwm.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x378027ba

INFO:gurobipy:Model fingerprint: 0x378027ba

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23608 rows and 3333 columns

INFO:gurobipy:Presolve removed 23608 rows and 3333 columns

Presolve time: 0.05s

INFO:gurobipy:Presolve time: 0.05s

Presolved: 1209 rows, 8715 columns, 20299 nonzeros

INFO:gurobipy:Presolved: 1209 rows, 8715 columns, 20299 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.952e+03

INFO:gurobipy: AA' NZ     : 3.952e+03

 Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.919e+04 (roughly 4 MB of memory)

 Factor Ops : 1.041e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.041e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.36665373e+13 -1.04636948e+13  5.67e+08 6.18e+01  1.92e+11     0s

INFO:gurobipy:   0   1.36665373e+13 -1.04636948e+13  5.67e+08 6.18e+01  1.92e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.08 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1404    2.1026344e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1404    2.1026344e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1404 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1404 iterations and 0.10 seconds (0.05 work units)

Optimal objective  2.102634441e+09

INFO:gurobipy:Optimal objective  2.102634441e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.10e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-09 00:00:00:2019-11-14 21:00:00] (53/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 84.76it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 244.04it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-641o063a.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-641o063a.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xbbed51b3

INFO:gurobipy:Model fingerprint: 0xbbed51b3

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23616 rows and 3326 columns

INFO:gurobipy:Presolve removed 23616 rows and 3326 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1201 rows, 8722 columns, 20298 nonzeros

INFO:gurobipy:Presolved: 1201 rows, 8722 columns, 20298 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.936e+03

INFO:gurobipy: AA' NZ     : 3.936e+03

 Factor NZ  : 2.725e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.725e+04 (roughly 4 MB of memory)

 Factor Ops : 8.720e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 8.720e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.70466251e+13 -8.68335006e+12  7.04e+08 5.97e+01  2.38e+11     0s

INFO:gurobipy:   0   1.70466251e+13 -8.68335006e+12  7.04e+08 5.97e+01  2.38e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1693    1.7908315e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1693    1.7908315e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1693 iterations and 0.09 seconds (0.05 work units)

INFO:gurobipy:Solved in 1693 iterations and 0.09 seconds (0.05 work units)

Optimal objective  1.790831466e+09

INFO:gurobipy:Optimal objective  1.790831466e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.79e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-15 00:00:00:2019-11-20 21:00:00] (54/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 85.97it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.70it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2i35l47r.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-2i35l47r.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xe2e51496

INFO:gurobipy:Model fingerprint: 0xe2e51496

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23617 rows and 3350 columns

INFO:gurobipy:Presolve removed 23617 rows and 3350 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1200 rows, 8698 columns, 20273 nonzeros

INFO:gurobipy:Presolved: 1200 rows, 8698 columns, 20273 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.934e+03

INFO:gurobipy: AA' NZ     : 3.934e+03

 Factor NZ  : 2.922e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.922e+04 (roughly 4 MB of memory)

 Factor Ops : 1.107e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.107e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.73493931e+13 -8.68149602e+12  7.17e+08 6.33e+01  2.42e+11     0s

INFO:gurobipy:   0   1.73493931e+13 -8.68149602e+12  7.17e+08 6.33e+01  2.42e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1414    1.9990937e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1414    1.9990937e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1414 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1414 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.999093716e+09

INFO:gurobipy:Optimal objective  1.999093716e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.00e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-21 00:00:00:2019-11-26 21:00:00] (55/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 86.05it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 237.91it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-tk5nhvsw.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-tk5nhvsw.lp

Reading time = 0.06 seconds

INFO:gurobipy:Reading time = 0.06 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x62e95afd

INFO:gurobipy:Model fingerprint: 0x62e95afd

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23622 rows and 3342 columns

INFO:gurobipy:Presolve removed 23622 rows and 3342 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1195 rows, 8706 columns, 20276 nonzeros

INFO:gurobipy:Presolved: 1195 rows, 8706 columns, 20276 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.01s

INFO:gurobipy:Ordering time: 0.01s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.924e+03

INFO:gurobipy: AA' NZ     : 3.924e+03

 Factor NZ  : 2.998e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.998e+04 (roughly 4 MB of memory)

 Factor Ops : 1.218e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.218e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.42783698e+13 -1.00941402e+13  5.90e+08 7.03e+01  2.00e+11     0s

INFO:gurobipy:   0   1.42783698e+13 -1.00941402e+13  5.90e+08 7.03e+01  2.00e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1444    2.1525577e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1444    2.1525577e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1444 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1444 iterations and 0.11 seconds (0.05 work units)

Optimal objective  2.152557696e+09

INFO:gurobipy:Optimal objective  2.152557696e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 2.15e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-11-27 00:00:00:2019-12-02 21:00:00] (56/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 84.35it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.18it/s]
INFO:linopy.io: Writing time: 0.26s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7sypwm88.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-7sypwm88.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x9feea860

INFO:gurobipy:Model fingerprint: 0x9feea860

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23628 rows and 3356 columns

INFO:gurobipy:Presolve removed 23628 rows and 3356 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1189 rows, 8692 columns, 20256 nonzeros

INFO:gurobipy:Presolved: 1189 rows, 8692 columns, 20256 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.913e+03

INFO:gurobipy: AA' NZ     : 3.913e+03

 Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

 Factor Ops : 1.158e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.158e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.44908957e+13 -9.92333904e+12  6.00e+08 7.42e+01  2.03e+11     0s

INFO:gurobipy:   0   1.44908957e+13 -9.92333904e+12  6.00e+08 7.42e+01  2.03e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1528    1.6890746e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1528    1.6890746e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1528 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1528 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.689074594e+09

INFO:gurobipy:Optimal objective  1.689074594e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.69e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-03 00:00:00:2019-12-08 21:00:00] (57/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.99it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 250.23it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-px14sd3x.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-px14sd3x.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x454195de

INFO:gurobipy:Model fingerprint: 0x454195de

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 1e+02]

INFO:gurobipy:  Bounds range     [1e+02, 1e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23628 rows and 3348 columns

INFO:gurobipy:Presolve removed 23628 rows and 3348 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1189 rows, 8700 columns, 20264 nonzeros

INFO:gurobipy:Presolved: 1189 rows, 8700 columns, 20264 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.913e+03

INFO:gurobipy: AA' NZ     : 3.913e+03

 Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.958e+04 (roughly 4 MB of memory)

 Factor Ops : 1.158e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.158e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.47260978e+13 -9.93032932e+12  6.11e+08 6.36e+01  2.06e+11     0s

INFO:gurobipy:   0   1.47260978e+13 -9.93032932e+12  6.11e+08 6.36e+01  2.06e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.09 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1654    1.3989273e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1654    1.3989273e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1654 iterations and 0.11 seconds (0.05 work units)

INFO:gurobipy:Solved in 1654 iterations and 0.11 seconds (0.05 work units)

Optimal objective  1.398927257e+09

INFO:gurobipy:Optimal objective  1.398927257e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.40e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-09 00:00:00:2019-12-14 21:00:00] (58/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 88.95it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 247.95it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-q6rz8m7_.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-q6rz8m7_.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0x1b8e4cb8

INFO:gurobipy:Model fingerprint: 0x1b8e4cb8

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 4e+00]

INFO:gurobipy:  Matrix range     [8e-03, 4e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [1e+02, 2e+02]

INFO:gurobipy:  Bounds range     [1e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23625 rows and 3339 columns

INFO:gurobipy:Presolve removed 23625 rows and 3339 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1192 rows, 8709 columns, 20276 nonzeros

INFO:gurobipy:Presolved: 1192 rows, 8709 columns, 20276 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.918e+03

INFO:gurobipy: AA' NZ     : 3.918e+03

 Factor NZ  : 2.866e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.866e+04 (roughly 4 MB of memory)

 Factor Ops : 1.036e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.036e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.84921756e+13 -8.54653957e+12  7.64e+08 5.87e+01  2.58e+11     0s

INFO:gurobipy:   0   1.84921756e+13 -8.54653957e+12  7.64e+08 5.87e+01  2.58e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.07 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1583    1.4382386e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1583    1.4382386e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1583 iterations and 0.10 seconds (0.05 work units)

INFO:gurobipy:Solved in 1583 iterations and 0.10 seconds (0.05 work units)

Optimal objective  1.438238594e+09

INFO:gurobipy:Optimal objective  1.438238594e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.44e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-15 00:00:00:2019-12-20 21:00:00] (59/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 79.85it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 243.81it/s]
INFO:linopy.io: Writing time: 0.27s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fo8dvo50.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-fo8dvo50.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xadd74ba4

INFO:gurobipy:Model fingerprint: 0xadd74ba4

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23623 rows and 3339 columns

INFO:gurobipy:Presolve removed 23623 rows and 3339 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1194 rows, 8709 columns, 20278 nonzeros

INFO:gurobipy:Presolved: 1194 rows, 8709 columns, 20278 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.922e+03

INFO:gurobipy: AA' NZ     : 3.922e+03

 Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.898e+04 (roughly 4 MB of memory)

 Factor Ops : 1.082e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.082e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.86777194e+13 -8.59268706e+12  7.72e+08 6.15e+01  2.61e+11     0s

INFO:gurobipy:   0   1.86777194e+13 -8.59268706e+12  7.72e+08 6.15e+01  2.61e+11     0s

   1   2.05573025e+12 -6.65450147e+12  8.45e+07 1.24e+04  2.90e+10     0s

INFO:gurobipy:   1   2.05573025e+12 -6.65450147e+12  8.45e+07 1.24e+04  2.90e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1688    1.1901622e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1688    1.1901622e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1688 iterations and 0.13 seconds (0.05 work units)

INFO:gurobipy:Solved in 1688 iterations and 0.13 seconds (0.05 work units)

Optimal objective  1.190162224e+09

INFO:gurobipy:Optimal objective  1.190162224e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.19e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-21 00:00:00:2019-12-26 21:00:00] (60/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 87.19it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 259.04it/s]
INFO:linopy.io: Writing time: 0.25s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-efsju2lm.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-efsju2lm.lp

Reading time = 0.05 seconds

INFO:gurobipy:Reading time = 0.05 seconds

obj: 24817 rows, 12048 columns, 48956 nonzeros

INFO:gurobipy:obj: 24817 rows, 12048 columns, 48956 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

INFO:gurobipy:Optimize a model with 24817 rows, 12048 columns and 48956 nonzeros

Model fingerprint: 0xa903fe48

INFO:gurobipy:Model fingerprint: 0xa903fe48

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 23621 rows and 3335 columns

INFO:gurobipy:Presolve removed 23621 rows and 3335 columns

Presolve time: 0.04s

INFO:gurobipy:Presolve time: 0.04s

Presolved: 1196 rows, 8713 columns, 20284 nonzeros

INFO:gurobipy:Presolved: 1196 rows, 8713 columns, 20284 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.926e+03

INFO:gurobipy: AA' NZ     : 3.926e+03

 Factor NZ  : 2.963e+04 (roughly 4 MB of memory)

INFO:gurobipy: Factor NZ  : 2.963e+04 (roughly 4 MB of memory)

 Factor Ops : 1.148e+06 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 1.148e+06 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.88465272e+13 -8.61528784e+12  7.79e+08 6.14e+01  2.63e+11     0s

INFO:gurobipy:   0   1.88465272e+13 -8.61528784e+12  7.79e+08 6.14e+01  2.63e+11     0s

   1   2.00590509e+12 -6.68401958e+12  8.24e+07 1.26e+04  2.83e+10     0s

INFO:gurobipy:   1   2.00590509e+12 -6.68401958e+12  8.24e+07 1.26e+04  2.83e+10     0s

INFO:gurobipy:

Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 1 iterations in 0.10 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1614    1.5736789e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1614    1.5736789e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1614 iterations and 0.12 seconds (0.05 work units)

INFO:gurobipy:Solved in 1614 iterations and 0.12 seconds (0.05 work units)

Optimal objective  1.573678854e+09

INFO:gurobipy:Optimal objective  1.573678854e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 12048 primals, 24817 duals
Objective: 1.57e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.
INFO:pypsa.optimization.abstract:Optimizing network for snapshot horizon [2019-12-27 00:00:00:2019-12-31 21:00:00] (61/61).
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
WARNING:pypsa.components:The following buses have no attached components, which can break the lopf:
{'EU', 'DE'}
INFO:linopy.model: Solve problem using Gurobi solver

Set parameter Username

INFO:gurobipy:Set parameter Username

Set parameter LicenseID to value 2637156

INFO:gurobipy:Set parameter LicenseID to value 2637156

Academic license - for non-commercial use only - expires 2026-03-16

INFO:gurobipy:Academic license - for non-commercial use only - expires 2026-03-16
INFO:linopy.io:Writing objective.
Writing constraints.: 100%|██████████| 17/17 [00:00<00:00, 97.88it/s]
Writing continuous variables.: 100%|██████████| 8/8 [00:00<00:00, 262.50it/s]
INFO:linopy.io: Writing time: 0.23s

Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ra8vwr9s.lp

INFO:gurobipy:Read LP format model from file /private/var/folders/1l/8dfp16zs2w581ykzgwkyg8nw0000gn/T/linopy-problem-ra8vwr9s.lp

Reading time = 0.04 seconds

INFO:gurobipy:Reading time = 0.04 seconds

obj: 20681 rows, 10040 columns, 40796 nonzeros

INFO:gurobipy:obj: 20681 rows, 10040 columns, 40796 nonzeros

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 24.4.0 24E263)

INFO:gurobipy:

CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

INFO:gurobipy:CPU model: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz

Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

INFO:gurobipy:

Optimize a model with 20681 rows, 10040 columns and 40796 nonzeros

INFO:gurobipy:Optimize a model with 20681 rows, 10040 columns and 40796 nonzeros

Model fingerprint: 0xfb9daaf9

INFO:gurobipy:Model fingerprint: 0xfb9daaf9

Coefficient statistics:

INFO:gurobipy:Coefficient statistics:

  Matrix range     [8e-03, 3e+00]

INFO:gurobipy:  Matrix range     [8e-03, 3e+00]

  Objective range  [3e-02, 6e+03]

INFO:gurobipy:  Objective range  [3e-02, 6e+03]

  Bounds range     [2e+02, 2e+02]

INFO:gurobipy:  Bounds range     [2e+02, 2e+02]

  RHS range        [1e-07, 2e+08]

INFO:gurobipy:  RHS range        [1e-07, 2e+08]

Presolve removed 19686 rows and 2791 columns

INFO:gurobipy:Presolve removed 19686 rows and 2791 columns

Presolve time: 0.03s

INFO:gurobipy:Presolve time: 0.03s

Presolved: 995 rows, 7249 columns, 16891 nonzeros

INFO:gurobipy:Presolved: 995 rows, 7249 columns, 16891 nonzeros

INFO:gurobipy:

Concurrent LP optimizer: dual simplex and barrier

INFO:gurobipy:Concurrent LP optimizer: dual simplex and barrier

Showing barrier log only...

INFO:gurobipy:Showing barrier log only...

INFO:gurobipy:

Ordering time: 0.00s

INFO:gurobipy:Ordering time: 0.00s

INFO:gurobipy:

Barrier statistics:

INFO:gurobipy:Barrier statistics:

 AA' NZ     : 3.268e+03

INFO:gurobipy: AA' NZ     : 3.268e+03

 Factor NZ  : 2.288e+04 (roughly 3 MB of memory)

INFO:gurobipy: Factor NZ  : 2.288e+04 (roughly 3 MB of memory)

 Factor Ops : 7.855e+05 (less than 1 second per iteration)

INFO:gurobipy: Factor Ops : 7.855e+05 (less than 1 second per iteration)

 Threads    : 1

INFO:gurobipy: Threads    : 1

INFO:gurobipy:

                  Objective                Residual

INFO:gurobipy:                  Objective                Residual

Iter       Primal          Dual         Primal    Dual     Compl     Time

INFO:gurobipy:Iter       Primal          Dual         Primal    Dual     Compl     Time

   0   1.46050189e+13 -8.77505079e+12  7.33e+08 6.17e+01  2.46e+11     0s

INFO:gurobipy:   0   1.46050189e+13 -8.77505079e+12  7.33e+08 6.17e+01  2.46e+11     0s

INFO:gurobipy:

Barrier performed 0 iterations in 0.12 seconds (0.03 work units)

INFO:gurobipy:Barrier performed 0 iterations in 0.12 seconds (0.03 work units)

Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:Barrier solve interrupted - model solved by another algorithm

INFO:gurobipy:

INFO:gurobipy:

Solved with dual simplex

INFO:gurobipy:Solved with dual simplex

Iteration    Objective       Primal Inf.    Dual Inf.      Time

INFO:gurobipy:Iteration    Objective       Primal Inf.    Dual Inf.      Time

    1340    1.5924368e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:    1340    1.5924368e+09   0.000000e+00   0.000000e+00      0s

INFO:gurobipy:

Solved in 1340 iterations and 0.16 seconds (0.04 work units)

INFO:gurobipy:Solved in 1340 iterations and 0.16 seconds (0.04 work units)

Optimal objective  1.592436823e+09

INFO:gurobipy:Optimal objective  1.592436823e+09
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 10040 primals, 20681 duals
Objective: 1.59e+09
Solver model: available
Solver message: 2

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Link-fix-p-lower, Link-fix-p-upper, Store-fix-e-lower, Store-fix-e-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance, Store-energy_balance were not assigned to the network.

Generation vergleich

In [29]:
gen = pd.DataFrame()
gen = pd.concat([gen, round(n_lt.statistics.supply(bus_carrier="AC").rename('N-LT') / 1e6)],axis=1)
gen = pd.concat([gen, round(n_rh_with_biomass.statistics.supply(bus_carrier="AC").rename('N-RH with Biomass') / 1e6)],axis=1)
gen = pd.concat([gen, round(n_rh_without_biomass.statistics.supply(bus_carrier="AC").rename('N-RH without Biomass') / 1e6)],axis=1) 
gen

                                              N-LT  N-RH with Biomass  \
Generator   Offshore Wind (AC)                28.0               30.0
            Offshore Wind (DC)               200.0              200.0
            Onshore Wind                     266.0              279.0
            Run of River                      15.0               15.0
            Solar                            155.0              157.0
            load-shedding                      0.0                1.0
            solar-hsat                       165.0              166.0
Link        CCGT                              26.0               25.0
            H2 Fuel Cell                       0.0                0.0
            H2 OCGT                            9.0                5.0
            H2 retrofit OCGT                   1.0                NaN
            Open-Cycle Gas                     0.0                0.0
            battery discharger                53.0               57.0
            coal                               3.0                2.0
            lignite                            8.0                2.0
            oil                                0.0                0.0
            solid biomass                      0.0                0.0
            urban central coal CHP             4.0                4.0
            urban central gas CHP             41.0               47.0
            urban central lignite CHP          0.0                0.0
            urban central oil CHP              0.0                0.0
            urban central solid biomass CHP    1.0                1.0
StorageUnit Pumped Hydro Storage               4.0                4.0
            Reservoir & Dam                    2.0                1.0

                                             N-RH without Biomass
Generator   Offshore Wind (AC)                               30.0
            Offshore Wind (DC)                              199.0
            Onshore Wind                                    278.0
            Run of River                                     15.0
            Solar                                           156.0
            load-shedding                                     0.0
            solar-hsat                                      164.0
Link        CCGT                                             21.0
            H2 Fuel Cell                                      0.0
            H2 OCGT                                           2.0
            H2 retrofit OCGT                                  NaN
            Open-Cycle Gas                                    0.0
            battery discharger                               57.0
            coal                                              1.0
            lignite                                           2.0
            oil                                               0.0
            solid biomass                                     0.0
            urban central coal CHP                            2.0
            urban central gas CHP                            25.0
            urban central lignite CHP                         0.0
            urban central oil CHP                             0.0
            urban central solid biomass CHP                  18.0
StorageUnit Pumped Hydro Storage                              4.0
            Reservoir & Dam                                   1.0

Preisvergleich

In [30]:
lmps = pd.DataFrame()

lmps = pd.concat([lmps, n_lt.buses_t.marginal_price['DE0 0'].rename('N-LT')], axis=1)
lmps = pd.concat([lmps, n_rh_with_biomass.buses_t.marginal_price['DE0 0'].rename('N-RH with Biomass')], axis=1)
lmps = pd.concat([lmps, n_rh_without_biomass.buses_t.marginal_price['DE0 0'].rename('N-RH without Biomass')], axis=1)


lmps.describe()

              N-LT  N-RH with Biomass  N-RH without Biomass
count  2920.000000        2920.000000           2920.000000
mean     96.629048         114.024058             97.280168
std     127.512748         213.435382            213.524392
min       0.035115           0.035117              0.035117
25%       0.058193          14.728103              0.528063
50%      62.483105          86.356153             61.899084
75%     127.399611         125.076188            120.439399
max    1401.208942        2000.010004           2000.010004

In [ ]:
networks = []

for i in range(0, nr_networks):
    
    n = n_lt.copy()
    add_carbon_price(n, co2_prices["2035"], specific_emissions_biomass) # mit biomass

    change_onwind_cf(n, i)
    change_offwind_cf(n, i)
    change_solar_cf(n, i)

    n = build_st_network(n)

    n.optimize.optimize_with_rolling_horizon(
        horizon = horizon,
        overlap = overlap,
        solver_name='gurobi'
    )

    networks.append(n)

In [38]:
n_lt.buses_t.marginal_price['EU solid biomass']

snapshot
2019-01-01 00:00:00    76.529662
2019-01-01 03:00:00    76.529662
2019-01-01 06:00:00    76.529662
2019-01-01 09:00:00    76.529662
2019-01-01 12:00:00    76.529662
                         ...
2019-12-31 09:00:00    76.529662
2019-12-31 12:00:00    76.529662
2019-12-31 15:00:00    76.529662
2019-12-31 18:00:00    76.529662
2019-12-31 21:00:00    76.529662
Name: EU solid biomass, Length: 2920, dtype: float64

In [39]:
n_rh_with_biomass.buses_t.marginal_price['EU solid biomass']

snapshot
2019-01-01 00:00:00    89.659376
2019-01-01 03:00:00    89.659376
2019-01-01 06:00:00    89.659376
2019-01-01 09:00:00    89.659376
2019-01-01 12:00:00    89.659376
                         ...
2019-12-31 09:00:00    89.659376
2019-12-31 12:00:00    89.659376
2019-12-31 15:00:00    89.659376
2019-12-31 18:00:00    89.659376
2019-12-31 21:00:00    89.659376
Name: EU solid biomass, Length: 2920, dtype: float64